# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""配置入口：全部来自环境变量，禁止在代码中出现任何密钥字面量。"""
import os
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Settings:
    project: str = "{{project_name}}"
    pack_ref: str = "{{pack_ref}}"
    # 业务人员后台页开关（闸门A 设计项，编译期写入；调试页与开发后台始终必含）
    business_console: bool = "{{business_console}}" == "true"

    redis_host: str = field(default_factory=lambda: os.getenv("IW_REDIS_HOST", "127.0.0.1"))
    redis_port: int = field(default_factory=lambda: int(os.getenv("IW_REDIS_PORT", "6379")))
    redis_password: str = field(default_factory=lambda: os.getenv("IW_REDIS_PASSWORD", ""))

    model_base_url: str = field(default_factory=lambda: os.getenv("IW_MODEL_BASE_URL", ""))
    model_name: str = field(default_factory=lambda: os.getenv("IW_MODEL_NAME", ""))
    model_api_key: str = field(default_factory=lambda: os.getenv("IW_MODEL_API_KEY", ""))

    core_mode: str = field(default_factory=lambda: os.getenv("IW_CORE_MODE", "mock"))
    mysql_host: str = field(default_factory=lambda: os.getenv("IW_MYSQL_HOST", "127.0.0.1"))
    mysql_port: int = field(default_factory=lambda: int(os.getenv("IW_MYSQL_PORT", "3306")))
    mysql_user: str = field(default_factory=lambda: os.getenv("IW_MYSQL_USER", "root"))
    mysql_password: str = field(default_factory=lambda: os.getenv("IW_MYSQL_PASSWORD", ""))
    mysql_database: str = field(default_factory=lambda: os.getenv("IW_MYSQL_DATABASE", "icewright_core"))


settings = Settings()
