// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
package assets

import "embed"

// FS 把 IceWright 编译进项目的领域产物打进二进制（与 java jar / python data 目录等价）。
//
//go:embed rules.json skills.json
var FS embed.FS
