// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package config 是配置入口：全部来自环境变量，禁止在代码中出现任何密钥字面量。
package config

import (
	"os"
	"strconv"
)

var (
	Project = "{{project_name}}"
	PackRef = "{{pack_ref}}"
	// BusinessConsole 是业务人员后台页开关（闸门A 设计项，编译期写入；调试页与开发后台始终必含）。
	BusinessConsole = "{{business_console}}" == "true"

	RedisHost     = envOr("IW_REDIS_HOST", "127.0.0.1")
	RedisPort     = envInt("IW_REDIS_PORT", 6379)
	RedisPassword = os.Getenv("IW_REDIS_PASSWORD")

	ModelBaseURL = os.Getenv("IW_MODEL_BASE_URL")
	ModelName    = os.Getenv("IW_MODEL_NAME")
	ModelAPIKey  = os.Getenv("IW_MODEL_API_KEY")

	CoreMode      = envOr("IW_CORE_MODE", "mock")
	MysqlHost     = envOr("IW_MYSQL_HOST", "127.0.0.1")
	MysqlPort     = envInt("IW_MYSQL_PORT", 3306)
	MysqlUser     = envOr("IW_MYSQL_USER", "root")
	MysqlPassword = os.Getenv("IW_MYSQL_PASSWORD")
	MysqlDatabase = envOr("IW_MYSQL_DATABASE", "icewright_core")

	// CallbackURL 是非实时交互回推回调（空=仅轮询 GET /messages/{msgid}/files）。
	CallbackURL = os.Getenv("IW_CALLBACK_URL")

	// AuthSecret 是身份验签共享密钥（空=调试模式免签；生产必配，配套 X-IW-* 请求头，见设计文档第 9 节）。
	AuthSecret = os.Getenv("IW_AUTH_SECRET")
)

func envOr(name, fallback string) string {
	if v := os.Getenv(name); v != "" {
		return v
	}
	return fallback
}

func envInt(name string, fallback int) int {
	if v := os.Getenv(name); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return fallback
}
