# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""核心系统接入层：本系统不落业务数据，事实一律实时取自对方核心系统。

mock 模式内置少量示例工单用于本地演示与评测；
mysql 模式只读查询对方核心系统表（示例结构，按 api-contract 适配）。
"""
import pymysql.cursors

from app.config.settings import settings

_MOCK_CLAIMS = {
    "CLM-0001": {"claim_status": "approved", "claim_amount": 3200.0, "claim_type": "vehicle_damage"},
    "CLM-0002": {"claim_status": "pending", "claim_amount": 800.0, "claim_type": "third_party"},
}


def _mysql_conn():
    return pymysql.connect(
        host=settings.mysql_host,
        port=settings.mysql_port,
        user=settings.mysql_user,
        password=settings.mysql_password,
        database=settings.mysql_database,
        cursorclass=pymysql.cursors.DictCursor,
        connect_timeout=3,
    )


def fetch_claim(claim_id: str) -> dict:
    if settings.core_mode == "mock":
        return dict(_MOCK_CLAIMS.get(claim_id, {}))
    with _mysql_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT status AS claim_status, amount AS claim_amount, type AS claim_type "
                "FROM claims WHERE claim_id = %s",
                (claim_id,),
            )
            row = cur.fetchone()
    return dict(row) if row else {}


def enrich(facts: dict) -> dict:
    """若会话里出现工单号，把核心系统实时字段并入事实集供规则匹配。"""
    claim_id = facts.get("claim_id") or facts.get("last_message", "")
    for known in _MOCK_CLAIMS if settings.core_mode == "mock" else ():
        if known in str(claim_id):
            facts["claim_id"] = known
    if facts.get("claim_id"):
        facts.update({k: v for k, v in fetch_claim(facts["claim_id"]).items()})
    return facts
