// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
package domain

import (
	"encoding/json"
	"fmt"

	"icewright.local/{{artifact_id}}/assets"
)

// APIContract 是编译进项目的单条接口契约（存在性经闸门A 人工确认）。
type APIContract = map[string]any

// LoadAPIs 读取 apis.json：仅供开发后台只读展示；
// 运行期事实数据一律走 integration.CoreClient，不回连契约端点。
func LoadAPIs() ([]APIContract, error) {
	raw, err := assets.FS.ReadFile("apis.json")
	if err != nil {
		return nil, fmt.Errorf("apis.json 读取失败: %w", err)
	}
	var payload struct {
		APIs []APIContract `json:"apis"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return nil, fmt.Errorf("apis.json 解析失败: %w", err)
	}
	return payload.APIs, nil
}
