// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
package domain

import (
	"reflect"
	"strings"
	"testing"
)

func TestNormalizeLanguage(t *testing.T) {
	cases := map[string]string{
		"":      "{{default_language}}",
		"zh":    "zh",
		" EN ":  "en",
		"en-US": "{{default_language}}", // 未知语种回退默认，绝不抛错
		"de":    "{{default_language}}",
	}
	for in, want := range cases {
		if got := Normalize(in); got != want {
			t.Errorf("Normalize(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestLanguagesSorted(t *testing.T) {
	got := Languages()
	want := []string{"en", "zh"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Languages() = %v, want %v", got, want)
	}
}

func TestTemplateSubstitutionBilingual(t *testing.T) {
	zh := T("transfer", "zh", map[string]string{"rule": "R0001"})
	if !strings.Contains(zh, "R0001") || strings.Contains(zh, "{rule}") {
		t.Errorf("zh 话术替换失败: %q", zh)
	}
	en := T("transfer", "en", map[string]string{"rule": "R0001"})
	if !strings.Contains(en, "R0001") || strings.Contains(en, "{rule}") {
		t.Errorf("en 话术替换失败: %q", en)
	}
	if zh == en {
		t.Error("中英话术不应相同")
	}
}

func TestModelLanguagePinned(t *testing.T) {
	if !strings.Contains(T("model_language", "en", nil), "English") {
		t.Error("en 应钉住英文回复")
	}
	if !strings.Contains(T("model_language", "zh", nil), "简体中文") {
		t.Error("zh 应钉住中文回复")
	}
}
