// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
package domain

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"strings"

	"icewright.local/{{artifact_id}}/assets"
)

// Fact 是会话事实集：槽位 + 核心系统实时字段。别名保证与 JSON 解码出的 map[string]any 完全同型。
type Fact = map[string]any

// Rule 是编译进项目的单条规则（结构由 api-contract 校验，这里只做宽松读取）。
type Rule = map[string]any

const fieldPrefix = "FLD-"

type condOp func(a, b any) bool

var ops = map[string]condOp{
	"==":       objEquals,
	"!=":       func(a, b any) bool { return !objEquals(a, b) },
	"<":        func(a, b any) bool { c, ok := compare(a, b); return ok && c < 0 },
	"<=":       func(a, b any) bool { c, ok := compare(a, b); return ok && c <= 0 },
	">":        func(a, b any) bool { c, ok := compare(a, b); return ok && c > 0 },
	">=":       func(a, b any) bool { c, ok := compare(a, b); return ok && c >= 0 },
	"in":       func(a, b any) bool { return containsValue(b, a) },
	"not_in":   func(a, b any) bool { return !containsValue(b, a) },
	"matches":  opMatches,
	"is_true":  func(a, b any) bool { return truthy(a) },
	"is_false": func(a, b any) bool { return !truthy(a) },
}

// LoadRules 读取编译进项目的 rules.json；文件缺失返回空表（S5 保证正常项目必存在）。
func LoadRules() ([]Rule, error) {
	raw, err := assets.FS.ReadFile("rules.json")
	if err != nil {
		return nil, fmt.Errorf("rules.json 读取失败: %w", err)
	}
	var wrapped struct {
		Rules []Rule `json:"rules"`
	}
	if err := json.Unmarshal(raw, &wrapped); err == nil && wrapped.Rules != nil {
		return wrapped.Rules, nil
	}
	var list []Rule
	if err := json.Unmarshal(raw, &list); err != nil {
		return nil, fmt.Errorf("rules.json 解析失败: %w", err)
	}
	return list, nil
}

func toFloat(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case float32:
		return float64(n), true
	case int:
		return float64(n), true
	case int64:
		return float64(n), true
	default:
		return 0, false
	}
}

// objEquals 数值按 float64 对齐（100 == 100.0），其余走深比较。
func objEquals(a, b any) bool {
	if av, ok := toFloat(a); ok {
		if bv, ok := toFloat(b); ok {
			return av == bv
		}
		return false
	}
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return reflect.DeepEqual(a, b)
}

func compare(a, b any) (int, bool) {
	if av, ok := toFloat(a); ok {
		if bv, ok := toFloat(b); ok {
			switch {
			case av < bv:
				return -1, true
			case av > bv:
				return 1, true
			default:
				return 0, true
			}
		}
		return 0, false
	}
	as, aok := a.(string)
	bs, bok := b.(string)
	if aok && bok {
		return strings.Compare(as, bs), true
	}
	return 0, false
}

func containsValue(haystack, needle any) bool {
	switch h := haystack.(type) {
	case []any:
		for _, item := range h {
			if objEquals(item, needle) {
				return true
			}
		}
		return false
	case string:
		n, ok := needle.(string)
		return ok && strings.Contains(h, n)
	case map[string]any:
		key, ok := needle.(string)
		if !ok {
			return false
		}
		_, exists := h[key]
		return exists
	default:
		return false
	}
}

func opMatches(a, b any) bool {
	s, ok1 := a.(string)
	expr, ok2 := b.(string)
	if !ok1 || !ok2 {
		return false
	}
	matched, err := regexp.MatchString(expr, s)
	return err == nil && matched
}

func truthy(a any) bool {
	switch v := a.(type) {
	case nil:
		return false
	case bool:
		return v
	case string:
		return v != ""
	case []any:
		return len(v) > 0
	case map[string]any:
		return len(v) > 0
	default:
		if n, ok := toFloat(a); ok {
			return n != 0
		}
		return true
	}
}

// lookupFact 支持规则条件引用数据字典 id（FLD-xxx），会话事实用槽位名——两种键都尝试。
func lookupFact(field string, facts Fact) (any, bool) {
	if v, ok := facts[field]; ok {
		return v, true
	}
	if strings.HasPrefix(field, fieldPrefix) {
		if v, ok := facts[strings.TrimPrefix(field, fieldPrefix)]; ok {
			return v, true
		}
	}
	return nil, false
}

func conditionMet(cond Rule, facts Fact) bool {
	opStr, _ := cond["op"].(string)
	op, ok := ops[opStr]
	if !ok {
		return false
	}
	field, _ := cond["field"].(string)
	value, found := lookupFact(field, facts)
	if !found {
		return false
	}
	return op(value, cond["value"])
}

func conditionsOf(rule Rule) []Rule {
	raw, ok := rule["conditions"]
	if !ok || raw == nil {
		raw = rule["condition"]
	}
	list, ok := raw.([]any)
	if !ok {
		return nil
	}
	out := make([]Rule, 0, len(list))
	for _, item := range list {
		if m, ok := item.(map[string]any); ok {
			out = append(out, Rule(m))
		}
	}
	return out
}

// RuleMatches condition_logic 缺省为 any（与契约默认值一致），空条件永不命中。
func RuleMatches(rule Rule, facts Fact) bool {
	conds := conditionsOf(rule)
	if len(conds) == 0 {
		return false
	}
	logic, _ := rule["condition_logic"].(string)
	all := logic == "all"
	for _, cond := range conds {
		met := conditionMet(cond, facts)
		if all && !met {
			return false
		}
		if !all && met {
			return true
		}
	}
	return all
}

func MatchRules(rules []Rule, facts Fact) []Rule {
	var out []Rule
	for _, rule := range rules {
		if RuleMatches(rule, facts) {
			out = append(out, rule)
		}
	}
	return out
}

func BlockingRules(rules []Rule) []Rule {
	var out []Rule
	for _, rule := range rules {
		if rule["enforcement_point"] == "pre_validator" {
			out = append(out, rule)
		}
	}
	return out
}

// PatternHitsMessage 对应 forbidden_pattern：关键词/正则直接扫描用户消息。
func PatternHitsMessage(rule Rule, message string) bool {
	list, ok := rule["patterns"].([]any)
	if !ok {
		return false
	}
	for _, item := range list {
		p, ok := item.(map[string]any)
		if !ok {
			continue
		}
		kind, _ := p["kind"].(string)
		expr, _ := p["expression"].(string)
		if expr == "" {
			continue
		}
		if kind == "keyword" && strings.Contains(message, expr) {
			return true
		}
		if kind == "regex" {
			if matched, err := regexp.MatchString(expr, message); err == nil && matched {
				return true
			}
		}
	}
	return false
}

func CollectPromptInjections(rules []Rule) []string {
	var out []string
	for _, rule := range rules {
		if rule["enforcement_point"] != "prompt_injection" {
			continue
		}
		if s, ok := rule["statement"].(string); ok && s != "" {
			out = append(out, s)
		}
	}
	return out
}

// DecisionFor 命中决策规则时返回 action 配置（kind ∈ transfer_human/set_slot/script/...），否则 nil。
func DecisionFor(rule Rule) map[string]any {
	if rule["type"] != "decision_rule" {
		return nil
	}
	if action, ok := rule["action"].(map[string]any); ok {
		return action
	}
	return nil
}
