// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
package domain

import (
	"reflect"
	"testing"
)

func TestLoadRulesFromEmbeddedData(t *testing.T) {
	rules, err := LoadRules()
	if err != nil {
		t.Fatalf("LoadRules 失败: %v", err)
	}
	if rules == nil {
		t.Fatal("rules 不应为 nil")
	}
}

func TestMatchRequiresAllConditions(t *testing.T) {
	rule := Rule{
		"id": "R0001", "type": "decision_rule", "condition_logic": "all",
		"conditions": []any{
			Rule{"field": "claim_status", "op": "==", "value": "approved"},
			Rule{"field": "claim_amount", "op": "<=", "value": 5000.0},
		},
		"enforcement_point": "prompt_injection",
	}
	if !RuleMatches(rule, Fact{"claim_status": "approved", "claim_amount": 100.0}) {
		t.Error("金额 100 应命中")
	}
	if RuleMatches(rule, Fact{"claim_status": "approved", "claim_amount": 9999.0}) {
		t.Error("金额 9999 不应命中")
	}
}

func TestMissingFieldNeverMatches(t *testing.T) {
	rule := Rule{
		"id": "R0002", "type": "decision_rule",
		"conditions":        []any{Rule{"field": "claim_status", "op": "==", "value": "approved"}},
		"enforcement_point": "prompt_injection",
	}
	if RuleMatches(rule, Fact{}) {
		t.Error("缺字段不应命中")
	}
}

func TestUnknownOpNeverMatches(t *testing.T) {
	rule := Rule{
		"id": "R0003", "type": "decision_rule",
		"conditions":        []any{Rule{"field": "x", "op": "~=~", "value": 1.0}},
		"enforcement_point": "prompt_injection",
	}
	if RuleMatches(rule, Fact{"x": 1.0}) {
		t.Error("未知 op 不应命中")
	}
}

func TestAnyLogic(t *testing.T) {
	rule := Rule{
		"id": "R0004", "type": "decision_rule", "condition_logic": "any",
		"conditions": []any{
			Rule{"field": "a", "op": "==", "value": 1.0},
			Rule{"field": "b", "op": "==", "value": 2.0},
		},
		"enforcement_point": "prompt_injection",
	}
	if !RuleMatches(rule, Fact{"a": 1.0, "b": 9.0}) {
		t.Error("任一命中即可")
	}
	if RuleMatches(rule, Fact{"a": 0.0, "b": 9.0}) {
		t.Error("全不命中不应匹配")
	}
}

func TestDictionaryIdFallsBackToSlotName(t *testing.T) {
	rule := Rule{
		"id":         "R0005",
		"conditions": []any{Rule{"field": "FLD-claim_status", "op": "==", "value": "approved"}},
	}
	if !RuleMatches(rule, Fact{"claim_status": "approved"}) {
		t.Error("FLD- 前缀应回退到槽位名")
	}
}

func TestForbiddenPatternScansMessage(t *testing.T) {
	rule := Rule{
		"id":   "R0006",
		"type": "forbidden_pattern",
		"patterns": []any{
			Rule{"kind": "keyword", "expression": "返点"},
			Rule{"kind": "regex", "expression": `\d{11}`},
		},
	}
	if !PatternHitsMessage(rule, "给我点返点吧") {
		t.Error("关键词应命中")
	}
	if !PatternHitsMessage(rule, "我的手机号13800138000") {
		t.Error("正则应命中")
	}
	if PatternHitsMessage(rule, "正常咨询理赔进度") {
		t.Error("正常语句不应命中")
	}
}

func TestNumericEqualityAcrossJsonTypes(t *testing.T) {
	rule := Rule{
		"id":         "R0007",
		"conditions": []any{Rule{"field": "amount", "op": "==", "value": 100.0}},
	}
	if !RuleMatches(rule, Fact{"amount": 100}) {
		t.Error("int 100 应等于 float 100.0")
	}
}

func TestPromptInjectionsCollected(t *testing.T) {
	rules := []Rule{
		{"id": "R1", "enforcement_point": "prompt_injection", "statement": "不得承诺赔付金额"},
		{"id": "R2", "enforcement_point": "pre_validator", "statement": "挡下"},
		{"id": "R3", "enforcement_point": "prompt_injection", "statement": ""},
	}
	got := CollectPromptInjections(rules)
	want := []string{"不得承诺赔付金额"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v want %v", got, want)
	}
}
