// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
package domain

import "testing"

func TestLoadSkillsFromEmbeddedData(t *testing.T) {
	skills, err := LoadSkills()
	if err != nil {
		t.Fatalf("LoadSkills 失败: %v", err)
	}
	if skills == nil {
		t.Fatal("skills 不应为 nil")
	}
}

func TestOnlyConfirmedSkillsEnabled(t *testing.T) {
	skills := []Skill{
		{"id": "SK-1", "status": "confirmed", "intents": []any{"check_claim"}},
		{"id": "SK-2", "status": "pending", "intents": []any{"refund"}},
		{"id": "SK-3", "intents": []any{"cancel"}},
	}
	enabled := Enabled(skills)
	if len(enabled) != 1 || enabled[0]["id"] != "SK-1" {
		t.Fatalf("仅 confirmed 应装载，got %v", enabled)
	}
}

func TestMatchIntentHitsConfirmedOnly(t *testing.T) {
	skills := []Skill{
		{"id": "SK-1", "status": "confirmed", "intents": []any{"check_claim", "query_status"}},
		{"id": "SK-2", "status": "pending", "intents": []any{"refund"}},
	}
	if got := MatchIntent(skills, "query_status"); got == nil || got["id"] != "SK-1" {
		t.Errorf("应命中 SK-1，got %v", got)
	}
	if got := MatchIntent(skills, "refund"); got != nil {
		t.Errorf("未确认技能不应命中，got %v", got)
	}
	if got := MatchIntent(skills, "unknown_intent"); got != nil {
		t.Errorf("无匹配意图应返回 nil，got %v", got)
	}
}
