// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
package domain

import (
	"encoding/json"
	"fmt"

	"icewright.local/{{artifact_id}}/assets"
)

// Skill 是编译进项目的单条技能绑定。
type Skill = map[string]any

// LoadSkills 读取 skills.json：仅闸门A 人工确认过的能力才可被激活。
func LoadSkills() ([]Skill, error) {
	raw, err := assets.FS.ReadFile("skills.json")
	if err != nil {
		return nil, fmt.Errorf("skills.json 读取失败: %w", err)
	}
	var payload struct {
		Skills []Skill `json:"skills"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return nil, fmt.Errorf("skills.json 解析失败: %w", err)
	}
	return payload.Skills, nil
}

// Enabled 过滤 status==confirmed；其余一律视为未装载（宁可不激活，不可误激活）。
func Enabled(skills []Skill) []Skill {
	var out []Skill
	for _, s := range skills {
		if s["status"] == "confirmed" {
			out = append(out, s)
		}
	}
	return out
}

// MatchIntent 在已确认技能里按意图命中第一项。
func MatchIntent(skills []Skill, intent string) Skill {
	for _, skill := range Enabled(skills) {
		list, ok := skill["intents"].([]any)
		if !ok {
			continue
		}
		for _, item := range list {
			if item == intent {
				return skill
			}
		}
	}
	return nil
}
