-- AUTO-GENERATED BY IceWright {{engine_version}} · init/schema.sql
-- ⚠ 示例契约，不是交付库脚本：本系统不落业务数据，对核心系统只读取数。
-- 本文件描述生成应用（IW_CORE_MODE=mysql 时）读取的表与字段的“契约形状”，
-- 供联调建演示库、或与客户真实核心系统表结构做对账映射之用。
-- 真实接入时以客户核心系统为准，按 init/README.md 的映射步骤调整集成层查询，
-- 不要把本 DDL 直接执行到客户生产库。

CREATE DATABASE IF NOT EXISTS icewright_core DEFAULT CHARSET utf8mb4;
USE icewright_core;

-- 工单/理赔单只读视图表（与 {{pack_ref}} 的 api-contract 对应）
CREATE TABLE IF NOT EXISTS claims (
    claim_id  VARCHAR(32)    NOT NULL COMMENT '工单号，会话槽位 claim_id 即查此键',
    status    VARCHAR(32)    NOT NULL COMMENT '状态：approved|pending|rejected 等，按契约枚举',
    amount    DECIMAL(12, 2) NOT NULL COMMENT '金额',
    type      VARCHAR(32)    NOT NULL COMMENT '类型：vehicle_damage|third_party 等',
    PRIMARY KEY (claim_id)
) ENGINE = InnoDB COMMENT 'IceWright 生成应用只读示例表（不落业务数据）';

-- 演示数据：与应用内置 mock 数据一致，方便 mock/mysql 两模式行为对齐
INSERT INTO claims (claim_id, status, amount, type)
VALUES ('CLM-0001', 'approved', 3200.00, 'vehicle_damage'),
       ('CLM-0002', 'pending', 800.00, 'third_party') ON DUPLICATE KEY
UPDATE status = VALUES(status),
       amount = VALUES(amount),
       type = VALUES(type);
