# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""非实时交互契约单测：msgid 幂等、异步文件回推、会话+msgid 命名空间隔离。

依赖 Redis（与真实部署一致）；不可达则整体跳过，不误报失败。
"""
import json
import time
from pathlib import Path
from uuid import uuid4

import pytest

from app.api import routes
from app.service import asyncmsg
from app.service import session as session_service

pytestmark = pytest.mark.skipif(
    session_service.redis_ping() != "ok", reason="Redis 不可达，异步契约测试跳过"
)


def _uid() -> str:
    """键带随机后缀：Redis 记录跨测试轮次存续，固定 msgid 会命中上轮缓存导致幂等断言失真。"""
    return uuid4().hex[:8]


def _req(session_id: str, message: str, msgid: str | None = None) -> routes.ChatRequest:
    return routes.ChatRequest(session_id=session_id, message=message, msgid=msgid)


def _counting_answers(monkeypatch) -> list:
    """把 chat_service.answer 包一层计数：幂等断言不依赖行业包规则会不会短路。"""
    calls: list = []
    original = asyncmsg.chat_service.answer

    def counting(session_id, message, language="zh"):
        calls.append((session_id, message))
        return original(session_id, message, language)

    monkeypatch.setattr(asyncmsg.chat_service, "answer", counting)
    return calls


def test_same_msgid_processed_once(monkeypatch):
    calls = _counting_answers(monkeypatch)
    s, m = "s-dup-%s" % _uid(), "m-dup-%s" % _uid()
    r1 = routes.chat(_req(s, "理赔需要哪些材料", m))
    r2 = routes.chat(_req(s, "理赔需要哪些材料", m))
    assert r1.model_dump() == r2.model_dump()
    assert len(calls) == 1


def test_different_msgid_both_processed(monkeypatch):
    calls = _counting_answers(monkeypatch)
    s = "s-two-%s" % _uid()
    routes.chat(_req(s, "第一句", "m-a-%s" % _uid()))
    routes.chat(_req(s, "第二句", "m-b-%s" % _uid()))
    assert len(calls) == 2


def test_msgid_charset_rejected():
    with pytest.raises(Exception):
        routes.ChatRequest(session_id="s", message="m", msgid="bad id/带空格")


def test_async_roundtrip_files_and_download():
    s, m = "s-async-%s" % _uid(), "m-async-%s" % _uid()
    accepted = routes.chat_async(_req(s, "帮我导出理赔材料清单", m))
    assert accepted["status"] == "accepted"
    view = _wait_done(s, m)
    assert view["status"] == "ready"
    assert len(view["files"]) == 1
    f = view["files"][0]
    assert f["download_url"].startswith("/messages/%s/files/" % m)
    resp = routes.message_file(m, f["file_id"], s)
    payload = json.loads(Path(resp.path).read_text(encoding="utf-8"))
    assert payload["session_id"] == s and payload["msgid"] == m
    assert payload["reply"]


def test_async_resubmit_is_idempotent():
    s, m = "s-re-%s" % _uid(), "m-re-%s" % _uid()
    routes.chat_async(_req(s, "重复提交测试", m))
    again = routes.chat_async(_req(s, "重复提交测试", m))
    assert again["status"] in ("accepted", "ready", "failed")
    _wait_done(s, m)
    # 幂等：二次受理没有再排任务——结果文件只有一份登记
    view = routes.message_files(m, s)
    assert len(view["files"]) == 1


def test_msgid_isolated_by_session_namespace():
    s_a, m = "s-iso-a-%s" % _uid(), "m-iso-%s" % _uid()
    routes.chat_async(_req(s_a, "甲会话消息", m))
    assert asyncmsg.record_of("s-iso-b-%s" % _uid(), m) is None
    view = _wait_done(s_a, m)
    assert view["status"] == "ready"
    with pytest.raises(Exception):
        routes.message_files(m, "s-iso-b-%s" % _uid())  # 裸 msgid 跨会话取不到


def _wait_done(session_id: str, msgid: str, timeout_s: float = 40.0) -> dict:
    # 上限须大于模型兜底超时：未配置模型时异步任务在模型超时后仍会落 ready/failed，不该被误判悬挂
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        view = routes.message_files(msgid, session_id)
        if view["status"] in ("ready", "failed"):
            return view
        time.sleep(0.05)
    raise AssertionError("异步任务未在 %ss 内落状态" % timeout_s)
