# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""技能注册表确定性单测：不依赖网络，也不依赖 skills.json 的具体内容。"""
from app.domain import skills


def test_load_skills_returns_list():
    assert isinstance(skills.load_skills(), list)


def test_only_confirmed_skills_enabled():
    sample = [
        {"id": "SK-a", "intents": ["x"], "status": "confirmed"},
        {"id": "SK-b", "intents": ["y"], "status": "pending"},
        {"id": "SK-c", "intents": ["z"]},
    ]
    assert [s["id"] for s in skills.enabled(sample)] == ["SK-a"]


def test_match_intent_respects_confirmation():
    sample = [
        {"id": "SK-a", "intents": ["x"], "status": "pending"},
        {"id": "SK-b", "intents": ["y", "w"], "status": "confirmed"},
    ]
    assert skills.match_intent(sample, "x") is None
    assert skills.match_intent(sample, "y") is not None
    assert skills.match_intent(sample, "y")["id"] == "SK-b"
    assert skills.match_intent(sample, "unknown") is None
