# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""i18n 目录与语言校验的确定性单测：不依赖网络与 Redis。"""
import pytest

from app.domain import i18n


def test_all_languages_cover_same_keys():
    keysets = [set(m) for m in i18n.MESSAGES.values()]
    assert keysets and all(k == keysets[0] for k in keysets)


def test_unknown_language_falls_back_to_default():
    assert i18n.normalize("fr") == i18n.DEFAULT_LANGUAGE
    assert i18n.t("takeover", "fr", rule="R-X") == i18n.t("takeover", "zh", rule="R-X")


def test_t_formats_params_per_language():
    zh = i18n.t("transfer", "zh", rule="R-1")
    en = i18n.t("transfer", "en", rule="R-1")
    assert "R-1" in zh and "R-1" in en
    assert zh != en


def test_chat_request_validates_language():
    pytest.importorskip("fastapi")
    import pydantic

    from app.api import routes

    assert routes.ChatRequest(session_id="s", message="hi").language == "zh"
    assert routes.ChatRequest(session_id="s", message="hi", language="en").language == "en"
    with pytest.raises(pydantic.ValidationError):
        routes.ChatRequest(session_id="s", message="hi", language="de")
