# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""身份与隔离契约单测：角色闸门、HMAC 验签、会话归属（用户/组隔离）、后台组过滤。

依赖 Redis（会话归属登记落 Redis sess: 键）；随机会话后缀避免跨轮次存续记录干扰断言。
"""
import dataclasses

import pytest
from uuid import uuid4

from app.api import routes
from app.config.settings import settings
from app.service import identity
from app.service import session as session_service
from app.service.identity import Identity, _sign, identify

pytestmark = pytest.mark.skipif(
    session_service.redis_ping() != "ok", reason="Redis 不可达，会话归属测试跳过"
)


def _patch_settings(monkeypatch, module, **overrides) -> None:
    """Settings 为 frozen dataclass：整包替换目标模块的 settings 引用而非改字段。"""
    monkeypatch.setattr(module, "settings", dataclasses.replace(settings, **overrides))


def _uid() -> str:
    return uuid4().hex[:8]


class _Req:
    """最小 Request 替身：identify 只读 headers。"""

    def __init__(self, headers: dict | None = None):
        self.headers = {k.lower(): v for k, v in (headers or {}).items()}


# —— identify：字符集 / 角色 / 验签 ——


def test_dev_mode_no_headers_is_local_developer(monkeypatch):
    _patch_settings(monkeypatch, identity, auth_secret="")
    ident = identify(_Req())
    assert (ident.user, ident.group, ident.role, ident.signed) == (
        "dev-local",
        "default",
        "developer",
        False,
    )


def test_bad_charset_rejected():
    with pytest.raises(Exception) as exc:
        identify(_Req({"X-IW-User": "bad user/带空格", "X-IW-Group": "g", "X-IW-Role": "customer"}))
    assert exc.value.status_code == 400


def test_unknown_role_rejected():
    with pytest.raises(Exception) as exc:
        identify(_Req({"X-IW-User": "u", "X-IW-Group": "g", "X-IW-Role": "superadmin"}))
    assert exc.value.status_code == 403


def test_signed_mode_requires_valid_sign(monkeypatch):
    _patch_settings(monkeypatch, identity, auth_secret="test-secret")
    headers = {"X-IW-User": "u1", "X-IW-Group": "g1", "X-IW-Role": "agent"}
    ident = identify(_Req(dict(headers, **{"X-IW-Sign": _sign("u1", "g1", "agent")})))
    assert ident.signed and ident.role == "agent"
    with pytest.raises(Exception) as exc:
        identify(_Req(dict(headers, **{"X-IW-Sign": "deadbeef"})))
    assert exc.value.status_code == 401
    with pytest.raises(Exception) as exc2:
        identify(_Req(headers))  # 缺签
    assert exc2.value.status_code == 401


def test_signed_mode_no_headers_is_401(monkeypatch):
    _patch_settings(monkeypatch, identity, auth_secret="test-secret")
    with pytest.raises(Exception) as exc:
        identify(_Req())
    assert exc.value.status_code == 401


# —— 会话归属：用户 / 组隔离 ——


def test_session_bound_to_first_owner_and_others_rejected():
    s = "s-own-%s" % _uid()
    owner = Identity("alice", "g1", "customer", False)
    identity.ensure_session(owner, s)
    other_user = Identity("bob", "g1", "customer", False)
    with pytest.raises(Exception) as exc:
        identity.ensure_session(other_user, s)
    assert exc.value.status_code == 403
    other_group = Identity("alice", "g2", "customer", False)
    with pytest.raises(Exception) as exc2:
        identity.ensure_session(other_group, s)
    assert exc2.value.status_code == 403
    dev = Identity("devx", "ops", "developer", False)
    identity.ensure_session(dev, s)  # developer 不受归属限制
    with pytest.raises(Exception) as exc3:
        identity.viewable(other_user, s)
    assert exc3.value.status_code == 403
    identity.viewable(owner, s)  # 所有者只读放行


def test_viewable_allows_unregistered_session():
    identity.viewable(Identity("anyone", "g", "customer", False), "s-none-%s" % _uid())


# —— 端点权限闸门 ——


def test_admin_requires_developer():
    with pytest.raises(Exception) as exc:
        routes.admin_overview(Identity("u", "g", "customer", False))
    assert exc.value.status_code == 403
    with pytest.raises(Exception) as exc2:
        routes.admin_overview(Identity("u", "g", "agent", False))
    assert exc2.value.status_code == 403
    overview = routes.admin_overview(Identity("u", "g", "developer", False))
    assert "auth_mode" in overview


def test_console_customer_rejected_agent_group_filtered(monkeypatch):
    _patch_settings(monkeypatch, routes, business_console=True)
    s1, s2 = "s-cg-a-%s" % _uid(), "s-cg-b-%s" % _uid()
    session_service.save_slots(s1, {"flagged": "r1", "turns": 3})
    session_service.set_json("sess:%s" % s1, {"user": "uA", "group": "ga"})
    session_service.save_slots(s2, {"flagged": "r1", "turns": 1})
    session_service.set_json("sess:%s" % s2, {"user": "uB", "group": "gb"})

    with pytest.raises(Exception) as exc:
        routes.console_sessions(Identity("u", "g", "customer", False))
    assert exc.value.status_code == 403

    rows_a = routes.console_sessions(Identity("op1", "ga", "agent", False))
    ids_a = [r["session_id"] for r in rows_a]
    assert s1 in ids_a and s2 not in ids_a  # agent 仅见本组

    rows_dev = routes.console_sessions(Identity("dev", "ops", "developer", False))
    ids_dev = [r["session_id"] for r in rows_dev]
    assert s1 in ids_dev and s2 in ids_dev  # developer 见全部
    row = next(r for r in rows_dev if r["session_id"] == s1)
    assert row["user"] == "uA" and row["group"] == "ga"


def test_console_disabled_returns_404(monkeypatch):
    _patch_settings(monkeypatch, routes, business_console=False)
    with pytest.raises(Exception) as exc:
        routes.console_sessions(Identity("dev", "ops", "developer", False))
    assert exc.value.status_code == 404
