# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""规则引擎确定性单测：不依赖网络与外部服务。"""
from app.domain import rules


def test_rules_artifact_loaded():
    loaded = rules.load_rules()
    assert isinstance(loaded, list)


def test_match_requires_all_conditions():
    rule = {
        "id": "R0001",
        "type": "decision_rule",
        "condition_logic": "all",
        "conditions": [
            {"field": "claim_status", "op": "==", "value": "approved"},
            {"field": "claim_amount", "op": "<=", "value": 5000},
        ],
        "enforcement_point": "prompt_injection",
        "action": {"reply_template": "可以直接赔付"},
    }
    assert rules.rule_matches(rule, {"claim_status": "approved", "claim_amount": 100})
    assert not rules.rule_matches(rule, {"claim_status": "approved", "claim_amount": 9999})


def test_missing_field_never_matches():
    rule = {
        "id": "R0002",
        "type": "decision_rule",
        "conditions": [{"field": "claim_status", "op": "==", "value": "approved"}],
        "enforcement_point": "prompt_injection",
    }
    assert not rules.rule_matches(rule, {})


def test_unknown_op_never_matches():
    rule = {
        "id": "R0003",
        "type": "decision_rule",
        "conditions": [{"field": "x", "op": "~=~", "value": 1}],
        "enforcement_point": "prompt_injection",
    }
    assert not rules.rule_matches(rule, {"x": 1})


def test_any_logic():
    rule = {
        "id": "R0004",
        "type": "decision_rule",
        "condition_logic": "any",
        "conditions": [
            {"field": "a", "op": "==", "value": 1},
            {"field": "b", "op": "==", "value": 2},
        ],
        "enforcement_point": "prompt_injection",
    }
    assert rules.rule_matches(rule, {"a": 1, "b": 9})
    assert not rules.rule_matches(rule, {"a": 0, "b": 9})
