# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""FastAPI 应用装配：只组装路由与生命周期，不含业务逻辑。"""
from fastapi import FastAPI

from app.api import routes

app = FastAPI(title="{{project_name}}", version="0.1.0")
app.include_router(routes.router)
