# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""固定话术的多语言目录：确定性回复按访客语言取值，未知语言回退默认语言。"""

MESSAGES = {
    "zh": {
        "pre_validator": "该请求触碰行业规则 {rule} 的硬性限制，已转人工处理。",
        "forbidden": "您的诉求已记录，但按行业规则 {rule} 该类请求需人工受理，正在为您转接。",
        "takeover": "检测到需要人工介入的情形（依据行业规则 {rule}），已为您转接人工客服。",
        "transfer": "该情形符合转人工条件（规则 {rule}），已为您排队人工客服。",
        "model_unavailable": "智能助手暂时不可用，已为您转接人工客服，请稍候。",
        "model_language": "请始终使用简体中文回复客户。",
    },
    "en": {
        "pre_validator": "Your request hits the hard limit of industry rule {rule} and has been transferred to a human agent.",
        "forbidden": "Your request has been noted, but rule {rule} requires human handling for this type of request. Transferring you now.",
        "takeover": "A situation requiring human intervention was detected (rule {rule}). You are being transferred to a human agent.",
        "transfer": "This case meets the escalation criteria (rule {rule}). A human agent will join shortly.",
        "model_unavailable": "The assistant is temporarily unavailable. Transferring you to a human agent, please hold on.",
        "model_language": "Always reply to the customer in English.",
    },
}

DEFAULT_LANGUAGE = "zh"


def normalize(language: str) -> str:
    lang = (language or "").strip().lower()
    return lang if lang in MESSAGES else DEFAULT_LANGUAGE


def t(key: str, language: str, **params) -> str:
    catalog = MESSAGES[normalize(language)]
    template = catalog.get(key) or MESSAGES[DEFAULT_LANGUAGE][key]
    return template.format(**params)
