# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""领域规则引擎：加载编译进项目的 rules.json，对会话事实做确定性匹配。

规则条目结构（由 IceWright S3 提取并经契约校验）：
  id / type / statement / enforcement_point / condition / action
condition 为 {field, op, value} 列表 + condition_logic(all|any)；
缺失字段的条件视为不匹配（宁可不触发，不可误触发）。
"""
import json
import re
from pathlib import Path
from typing import Any

RULES_PATH = Path(__file__).resolve().parents[1] / "data" / "rules.json"


def _op_matches(a: Any, b: Any) -> bool:
    return isinstance(a, str) and isinstance(b, str) and re.search(b, a) is not None


_OPS = {
    "==": lambda a, b: a == b,
    "!=": lambda a, b: a != b,
    "<": lambda a, b: a < b,
    "<=": lambda a, b: a <= b,
    ">": lambda a, b: a > b,
    ">=": lambda a, b: a >= b,
    "in": lambda a, b: a in b,
    "not_in": lambda a, b: a not in b,
    "matches": _op_matches,
    "is_true": lambda a, b: bool(a),
    "is_false": lambda a, b: not a,
}


def load_rules() -> list[dict]:
    payload = json.loads(RULES_PATH.read_text(encoding="utf-8"))
    rules = payload.get("rules", []) if isinstance(payload, dict) else payload
    return [r for r in rules if isinstance(r, dict)]


def _lookup_fact(field: str, facts: dict):
    """规则条件引用数据字典 id（FLD-xxx），会话事实用槽位名——两种键都尝试。"""
    if field in facts:
        return True, facts[field]
    if field.startswith("FLD-") and field[4:] in facts:
        return True, facts[field[4:]]
    return False, None


def _condition_met(cond: dict, facts: dict) -> bool:
    op = _OPS.get(cond.get("op", ""))
    if op is None:
        return False
    found, value = _lookup_fact(cond.get("field", ""), facts)
    if not found:
        return False
    try:
        return bool(op(value, cond.get("value")))
    except TypeError:
        return False


def rule_matches(rule: dict, facts: dict) -> bool:
    conds = rule.get("conditions") or rule.get("condition") or []
    if not conds:
        return False
    logic = rule.get("condition_logic", "any")  # 与契约默认值一致
    results = [_condition_met(c, facts) for c in conds]
    return all(results) if logic == "all" else any(results)


def match_rules(rules: list[dict], facts: dict) -> list[dict]:
    return [r for r in rules if rule_matches(r, facts)]


def blocking_rules(rules: list[dict]) -> list[dict]:
    return [r for r in rules if r.get("enforcement_point") == "pre_validator"]


def pattern_hits_message(rule: dict, message: str) -> bool:
    """forbidden_pattern：关键词/正则直接扫描用户消息。"""
    for p in rule.get("patterns", []):
        kind = p.get("kind")
        expr = p.get("expression", "")
        if not expr:
            continue
        if kind == "keyword" and expr in message:
            return True
        if kind == "regex":
            try:
                if re.search(expr, message):
                    return True
            except re.error:
                pass
    return False


def collect_prompt_injections(rules: list[dict]) -> list[str]:
    return [
        r.get("statement", "")
        for r in rules
        if r.get("enforcement_point") == "prompt_injection" and r.get("statement")
    ]


def decision_for(rule: dict, facts: dict) -> Any:
    """命中决策规则时返回 action 配置（kind ∈ transfer_human/set_slot/script/...），否则 None。"""
    if rule.get("type") == "decision_rule":
        action = rule.get("action")
        return action if isinstance(action, dict) else None
    return None
