# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""技能注册表：加载编译进项目的 skills.json，仅放行闸门A 人工确认过的能力。

技能条目结构（由 IceWright S3 提取并经契约校验）：
  id / name / intents / capability{kind, ref, ...} / required_fields / rule_refs / status
status 非 confirmed 一律视为未装载（宁可不激活，不可误激活）。
"""
import json
from pathlib import Path
from typing import Any, Optional

SKILLS_PATH = Path(__file__).resolve().parents[1] / "data" / "skills.json"


def load_skills() -> list[dict[str, Any]]:
    if not SKILLS_PATH.exists():
        return []
    data = json.loads(SKILLS_PATH.read_text(encoding="utf-8"))
    return list(data.get("skills", []))


def enabled(skills: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [s for s in skills if s.get("status") == "confirmed"]


def match_intent(skills: list[dict[str, Any]], intent: str) -> Optional[dict[str, Any]]:
    for skill in enabled(skills):
        if intent in skill.get("intents", []):
            return skill
    return None
