# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""非实时交互：msgid 幂等合并 + 异步处理 + 文件回推。

契约（与设计文档第 8 节一致，三栈同形）：
- 入站消息带 msgid 时按 `msg:{session_id}:{msgid}` 登记幂等记录，重发不重复处理；
- 异步任务的结果文件落盘 data/files/（默认本地实现，可整层替换：save_file/load_file 即接口），
  Redis 只存 `msg:{session_id}:{msgid}` → 状态+文件标识 映射（带 TTL），不落业务数据本体；
- 取回凭 session_id+msgid 双段键，严禁裸 msgid 全局键，多会话互不串扰；
- 配了 IW_CALLBACK_URL 则处理完成时推送一次（尽力而为，失败不影响轮取回；消费端按 msgid 幂等）。
"""
import json
import urllib.request
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

from app.config.settings import settings
from app.service import chat as chat_service
from app.service import session as session_service

MSG_TTL_SECONDS = 3600
FILES_DIR = Path(__file__).resolve().parents[1] / "data" / "files"
CALLBACK_TIMEOUT_SECONDS = 5

# 小容量固定线程池：异步任务并行的默认实现，客户有编排系统可替换本模块执行器
_EXECUTOR = ThreadPoolExecutor(max_workers=4, thread_name_prefix="iw-async")


def _suffix(session_id: str, msgid: str) -> str:
    return "msg:%s:%s" % (session_id, msgid)


def record_of(session_id: str, msgid: str) -> dict | None:
    return session_service.get_json(_suffix(session_id, msgid))


def _put(session_id: str, msgid: str, record: dict) -> None:
    session_service.set_json(_suffix(session_id, msgid), record, MSG_TTL_SECONDS)


def save_file(content: dict) -> str:
    """结果文件落盘（默认实现=本地 data/files，换共享存储只改本函数与 load_file）。"""
    file_id = uuid.uuid4().hex
    FILES_DIR.mkdir(parents=True, exist_ok=True)
    (FILES_DIR / (file_id + ".json")).write_text(
        json.dumps(content, ensure_ascii=False), encoding="utf-8"
    )
    return file_id


def load_file(file_id: str) -> Path | None:
    """按服务端生成的 file_id 取文件；只认 .json 快照，杜绝路径穿越。"""
    if not file_id.isalnum():
        return None
    path = FILES_DIR / (file_id + ".json")
    return path if path.exists() else None


def answer_idempotent(session_id: str, msgid: str, message: str, language: str) -> dict:
    """同步 /chat 的 msgid 支路：已处理过直接回放原回执（不重复计轮、不重发副作用）。"""
    if not msgid:
        return chat_service.answer(session_id, message, language)
    record = record_of(session_id, msgid)
    if record and record.get("status") == "ready" and isinstance(record.get("reply"), dict):
        return record["reply"]
    result = chat_service.answer(session_id, message, language)
    _put(session_id, msgid, {"status": "ready", "reply": result, "files": []})
    return result


def accept_async(session_id: str, msgid: str, message: str, language: str) -> tuple[str, str]:
    """受理异步请求：重复 msgid 幂等返回既有状态，不再投任务。"""
    mid = msgid or uuid.uuid4().hex
    record = record_of(session_id, mid)
    if record is not None:
        return mid, str(record.get("status", "accepted"))
    _put(session_id, mid, {"status": "accepted", "reply": None, "files": []})
    _EXECUTOR.submit(_run, session_id, mid, message, language)
    return mid, "accepted"


def _run(session_id: str, msgid: str, message: str, language: str) -> None:
    try:
        result = chat_service.answer(session_id, message, language)
        file_id = save_file({"session_id": session_id, "msgid": msgid, **result})
        files = [{"file_id": file_id, "name": "reply-%s.json" % msgid}]
        _put(session_id, msgid, {"status": "ready", "reply": result, "files": files})
        _callback(session_id, msgid, files)
    except Exception as exc:  # noqa: BLE001 异步任务失败必须落状态，绝不留悬挂 accepted
        _put(session_id, msgid, {"status": "failed", "error": str(exc), "files": []})


def _callback(session_id: str, msgid: str, files: list[dict[str, str]]) -> None:
    """推送模式（可选）：webhook 携带同一 file_id，消费端按 msgid 幂等重放安全。"""
    url = settings.callback_url
    if not url:
        return
    payload = json.dumps(
        {"session_id": session_id, "msgid": msgid, "files": files}, ensure_ascii=False
    ).encode("utf-8")
    request = urllib.request.Request(
        url, data=payload, headers={"Content-Type": "application/json"}, method="POST"
    )
    try:
        with urllib.request.urlopen(request, timeout=CALLBACK_TIMEOUT_SECONDS):
            pass
    except Exception:  # noqa: BLE001 回调失败不影响轮询取回
        pass


def files_view(session_id: str, msgid: str) -> dict[str, Any] | None:
    """轮询视图：状态 + 可下载文件清单；未登记（或已过 TTL）返回 None。"""
    record = record_of(session_id, msgid)
    if record is None:
        return None
    status = str(record.get("status", "accepted"))
    files = [
        {
            **f,
            "download_url": "/messages/%s/files/%s?session_id=%s"
            % (msgid, f["file_id"], session_id),
        }
        for f in record.get("files", [])
    ]
    return {
        "session_id": session_id,
        "msgid": msgid,
        "status": "pending" if status == "accepted" else status,
        "files": files,
    }
