# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""对话服务：确定性规则优先，规则未覆盖处才调用大模型，模型不可用则友好兜底。"""
import json
import urllib.error
import urllib.request

from app.config.settings import settings
from app.domain import i18n
from app.domain import rules as rule_engine
from app.integration import core_client
from app.service import session as session_service

LLM_TIMEOUT_SECONDS = 30


def _chat_url() -> str:
    return settings.model_base_url.rstrip("/") + "/chat/completions"


def _call_model(message: str, injections: list[str], language: str) -> str:
    system = "你是客服系统「%s」，遵守以下行业规则要求作答：\n%s\n%s" % (
        settings.project,
        "\n".join("- " + s for s in injections) or "- 无附加规则",
        i18n.t("model_language", language),
    )
    body = json.dumps(
        {
            "model": settings.model_name,
            "temperature": 0,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": message},
            ],
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        _chat_url(),
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer " + settings.model_api_key,
        },
    )
    with urllib.request.urlopen(req, timeout=LLM_TIMEOUT_SECONDS) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return payload["choices"][0]["message"]["content"]


def answer(session_id: str, message: str, language: str = "zh") -> dict:
    lang = i18n.normalize(language)
    rules = rule_engine.load_rules()
    slots = session_service.load_slots(session_id)
    facts = dict(slots)
    facts["last_message"] = message
    core_client.enrich(facts)

    matched = rule_engine.match_rules(rules, facts)
    matched_ids = [str(r.get("id", "")) for r in matched]

    def done(reply_key: str, rule_id: str = "") -> dict:
        reply = i18n.t(reply_key, lang, rule=rule_id) if rule_id else i18n.t(reply_key, lang)
        return {
            "session_id": session_id,
            "reply": reply,
            "matched_rules": matched_ids,
            "language": lang,
        }

    # 1) 硬拦截：pre_validator 规则命中即挡下，绝不进模型
    for r in matched:
        if r.get("enforcement_point") == "pre_validator":
            return done("pre_validator", str(r.get("id", "")))

    # 2) 禁语扫描：forbidden_pattern 直接匹配用户消息
    for r in rules:
        if r.get("type") == "forbidden_pattern" and rule_engine.pattern_hits_message(r, message):
            return done("forbidden", str(r.get("id", "")))

    # 3) 升级/接管类：命中即转人工并给出规则依据（原因必须可追溯）
    for r in matched:
        if r.get("enforcement_point") == "takeover":
            return done("takeover", str(r.get("id", "")))

    # 4) 决策规则：可确定性处置的不走模型
    for r in matched:
        action = rule_engine.decision_for(r, facts)
        if not action:
            continue
        kind = action.get("kind")
        if kind == "transfer_human":
            return done("transfer", str(r.get("id", "")))
        if kind == "set_slot":
            slots = session_service.merge_slots(session_id, action.get("set") or {})
            facts.update(slots)

    try:
        reply = _call_model(message, rule_engine.collect_prompt_injections(rules), lang)
    except (urllib.error.URLError, KeyError, TimeoutError, OSError, ValueError):
        reply = i18n.t("model_unavailable", lang)

    session_service.merge_slots(session_id, {"turns": int(slots.get("turns", 0)) + 1})
    return {
        "session_id": session_id,
        "reply": reply,
        "matched_rules": matched_ids,
        "language": lang,
    }
