# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""对话服务：确定性规则优先，规则未覆盖处才走 AgentScope 智能体；框架/模型不可用则友好兜底。

模型调用一律经 AgentScope 框架（OpenAIChatModel + Agent），不自研 HTTP 协议层；
端点/模型/密钥全部来自环境变量（BYOK，OpenAI-compatible 皆可接入）。
"""
import asyncio

from app.config.settings import settings
from app.domain import i18n
from app.domain import rules as rule_engine
from app.integration import core_client
from app.service import session as session_service

LLM_TIMEOUT_SECONDS = 30


def _text_of(message) -> str:
    """把回复中的 text 块拼成纯文本。"""
    return "".join(
        block.text for block in message.content if getattr(block, "type", None) == "text"
    )


def _require_configured() -> None:
    if not (settings.model_base_url and settings.model_name and settings.model_api_key):
        raise RuntimeError("模型未配置（IW_MODEL_BASE_URL/IW_MODEL_NAME/IW_MODEL_API_KEY）")


def _user_msg(text: str):
    from agentscope.message import Msg, TextBlock

    return Msg(name="user", content=[TextBlock(type="text", text=text)], role="user")


async def _agent_reply(message: str, injections: list[str], language: str) -> str:
    from agentscope.agent import Agent
    from agentscope.credential import OpenAICredential
    from agentscope.model import OpenAIChatModel

    _require_configured()
    system = "你是客服系统「%s」，遵守以下行业规则要求作答：\n%s\n%s\n%s" % (
        settings.project,
        "\n".join("- " + s for s in injections) or "- 无附加规则",
        i18n.t("model_language", language),
        i18n.t("model_guard", language),
    )
    model = OpenAIChatModel(
        credential=OpenAICredential(
            api_key=settings.model_api_key,
            base_url=settings.model_base_url,
        ),
        model=settings.model_name,
        parameters=OpenAIChatModel.Parameters(temperature=0),
        stream=False,
        client_kwargs={"timeout": LLM_TIMEOUT_SECONDS},
    )
    agent = Agent(name="customer-service", system_prompt=system, model=model)
    reply = await agent.reply(_user_msg(message))
    return _text_of(reply)


def _call_model(message: str, injections: list[str], language: str) -> str:
    return asyncio.run(_agent_reply(message, injections, language))


def answer(session_id: str, message: str, language: str = "{{default_language}}") -> dict:
    lang = i18n.normalize(language)
    rules = rule_engine.load_rules()
    slots = session_service.load_slots(session_id)
    facts = dict(slots)
    facts["last_message"] = message
    core_client.enrich(facts)

    matched = rule_engine.match_rules(rules, facts)
    matched_ids = [str(r.get("id", "")) for r in matched]

    def done(reply_key: str, rule_id: str = "") -> dict:
        reply = i18n.t(reply_key, lang, rule=rule_id) if rule_id else i18n.t(reply_key, lang)
        # 短路命中的会话打标，供业务后台 /console 列出待人工关注（只标规则 id，不存业务数据）
        if rule_id:
            session_service.merge_slots(session_id, {"flagged": rule_id})
        return {
            "session_id": session_id,
            "reply": reply,
            "matched_rules": matched_ids,
            "language": lang,
        }

    # 1) 硬拦截：pre_validator 规则命中即挡下，绝不进模型
    for r in matched:
        if r.get("enforcement_point") == "pre_validator":
            return done("pre_validator", str(r.get("id", "")))

    # 2) 禁语扫描：forbidden_pattern 直接匹配用户消息
    for r in rules:
        if r.get("type") == "forbidden_pattern" and rule_engine.pattern_hits_message(r, message):
            return done("forbidden", str(r.get("id", "")))

    # 3) 升级/接管类：命中即转人工并给出规则依据（原因必须可追溯）
    for r in matched:
        if r.get("enforcement_point") == "takeover":
            return done("takeover", str(r.get("id", "")))

    # 4) 决策规则：可确定性处置的不走模型
    for r in matched:
        action = rule_engine.decision_for(r, facts)
        if not action:
            continue
        kind = action.get("kind")
        if kind == "transfer_human":
            return done("transfer", str(r.get("id", "")))
        if kind == "set_slot":
            slots = session_service.merge_slots(session_id, action.get("set") or {})
            facts.update(slots)

    try:
        reply = _call_model(message, rule_engine.collect_prompt_injections(rules), lang)
    except Exception:  # noqa: BLE001 - 框架/网络/配置任何失败都兜底，绝不 500
        reply = i18n.t("model_unavailable", lang)

    session_service.merge_slots(session_id, {"turns": int(slots.get("turns", 0)) + 1})
    return {
        "session_id": session_id,
        "reply": reply,
        "matched_rules": matched_ids,
        "language": lang,
    }
