# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""对话服务：确定性规则优先，规则未覆盖处才调用大模型，模型不可用则友好兜底。"""
import json
import urllib.error
import urllib.request

from app.config.settings import settings
from app.domain import rules as rule_engine
from app.integration import core_client
from app.service import session as session_service

LLM_TIMEOUT_SECONDS = 30


def _chat_url() -> str:
    return settings.model_base_url.rstrip("/") + "/chat/completions"


def _call_model(message: str, injections: list[str]) -> str:
    system = "你是客服系统「%s」，遵守以下行业规则要求作答：\n%s" % (
        settings.project,
        "\n".join("- " + s for s in injections) or "- 无附加规则",
    )
    body = json.dumps(
        {
            "model": settings.model_name,
            "temperature": 0,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": message},
            ],
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        _chat_url(),
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer " + settings.model_api_key,
        },
    )
    with urllib.request.urlopen(req, timeout=LLM_TIMEOUT_SECONDS) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return payload["choices"][0]["message"]["content"]


def answer(session_id: str, message: str) -> dict:
    rules = rule_engine.load_rules()
    slots = session_service.load_slots(session_id)
    facts = dict(slots)
    facts["last_message"] = message
    core_client.enrich(facts)

    matched = rule_engine.match_rules(rules, facts)
    matched_ids = [str(r.get("id", "")) for r in matched]

    # 1) 硬拦截：pre_validator 规则命中即挡下，绝不进模型
    for r in matched:
        if r.get("enforcement_point") == "pre_validator":
            reply = "该请求触碰行业规则 %s 的硬性限制，已转人工处理。" % r.get("id", "")
            return {"session_id": session_id, "reply": reply, "matched_rules": matched_ids}

    # 2) 禁语扫描：forbidden_pattern 直接匹配用户消息
    for r in rules:
        if r.get("type") == "forbidden_pattern" and rule_engine.pattern_hits_message(r, message):
            reply = "您的诉求已记录，但按行业规则 %s 该类请求需人工受理，正在为您转接。" % r.get("id", "")
            return {"session_id": session_id, "reply": reply, "matched_rules": matched_ids}

    # 3) 决策规则：可确定性处置的不走模型
    for r in matched:
        action = rule_engine.decision_for(r, facts)
        if not action:
            continue
        kind = action.get("kind")
        if kind == "transfer_human":
            reply = "该情形符合转人工条件（规则 %s），已为您排队人工客服。" % r.get("id", "")
            return {"session_id": session_id, "reply": reply, "matched_rules": matched_ids}
        if kind == "set_slot":
            slots = session_service.merge_slots(session_id, action.get("set") or {})
            facts.update(slots)

    try:
        reply = _call_model(message, rule_engine.collect_prompt_injections(rules))
    except (urllib.error.URLError, KeyError, TimeoutError, OSError, ValueError):
        reply = "智能助手暂时不可用，已为您转接人工客服，请稍候。"

    session_service.merge_slots(session_id, {"turns": int(slots.get("turns", 0)) + 1})
    return {"session_id": session_id, "reply": reply, "matched_rules": matched_ids}
