# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""身份与隔离：组 / 会话 / 用户 / 用户类型四层隔离的框架层实现。

默认实现=客户网关注入 X-IW-User / X-IW-Group / X-IW-Role 头 + HMAC-SHA256 共享密钥验签
（IW_AUTH_SECRET）；客户已有统一认证体系（OAuth/SSO/自有签名）时只替换 identify 一个函数，
业务代码不动。权限闸门收口在 HTTP 层，不依赖模型自觉（设计文档第 9 节）。
"""
import hmac
import re
from dataclasses import dataclass
from hashlib import sha256

from fastapi import HTTPException, Request

from app.config.settings import settings
from app.service import session as session_service

ROLES = ("developer", "agent", "customer")
_ID_PATTERN = re.compile(r"^[A-Za-z0-9_.:-]{1,128}$")


@dataclass(frozen=True)
class Identity:
    user: str
    group: str
    role: str
    signed: bool


def dev_mode() -> bool:
    """未配置共享密钥即调试模式：免签、头缺省记名 anon 终端用户（运行总览明文告警）。"""
    return not settings.auth_secret


def _sign(user: str, group: str, role: str) -> str:
    payload = "%s|%s|%s" % (user, group, role)
    return hmac.new(settings.auth_secret.encode(), payload.encode(), sha256).hexdigest()


def identify(request: Request) -> Identity:
    """解析并校验身份头；验签失败 401，角色非法 403，标识字符集非法 400。

    调试模式（未配 IW_AUTH_SECRET）下不带任何头=本机开发者，直连后台页面可用；
    一旦配置密钥，所有请求都必须带签名头——生产环境无免签通道。
    """
    user = request.headers.get("x-iw-user", "")
    group = request.headers.get("x-iw-group", "")
    role = request.headers.get("x-iw-role", "")
    if not (user or group or role):
        if not dev_mode():
            raise HTTPException(status_code=401, detail="缺少身份请求头（X-IW-User/X-IW-Group/X-IW-Role）")
        return Identity("dev-local", "default", "developer", signed=False)
    if not (_ID_PATTERN.match(user) and _ID_PATTERN.match(group)):
        raise HTTPException(status_code=400, detail="user/group 标识字符集非法")
    if role not in ROLES:
        raise HTTPException(status_code=403, detail="用户类型不在允许集合: %s" % role)
    if not dev_mode() and not hmac.compare_digest(_sign(user, group, role), request.headers.get("x-iw-sign", "")):
        raise HTTPException(status_code=401, detail="签名校验失败（X-IW-Sign 与共享密钥不符）")
    return Identity(user, group, role, signed=not dev_mode())


def _owner_of(session_id: str) -> dict | None:
    return session_service.get_json("sess:%s" % session_id)


def ensure_session(ident: Identity, session_id: str) -> None:
    """会话首用绑定 用户+组；此后仅所有者或 developer 可用（活跃即续期）。"""
    owner = _owner_of(session_id)
    if owner is None:
        session_service.set_json("sess:%s" % session_id, {"user": ident.user, "group": ident.group})
        return
    if ident.role != "developer" and (owner.get("user") != ident.user or owner.get("group") != ident.group):
        raise HTTPException(status_code=403, detail="会话归属其他用户或组（会话/用户/组隔离生效）")
    session_service.set_json("sess:%s" % session_id, owner)


def viewable(ident: Identity, session_id: str) -> None:
    """只读校验（不登记归属）：developer 全量可见，其余须与登记所有者同用户同组。"""
    owner = _owner_of(session_id)
    if (
        owner is not None
        and ident.role != "developer"
        and (owner.get("user") != ident.user or owner.get("group") != ident.group)
    ):
        raise HTTPException(status_code=403, detail="会话归属其他用户或组（会话/用户/组隔离生效）")


def require_role(ident: Identity, *roles: str) -> None:
    if ident.role not in roles:
        raise HTTPException(
            status_code=403,
            detail="该端点仅限 %s，当前用户类型: %s" % ("/".join(roles), ident.role),
        )
