# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""会话槽位存储：Redis 只存易失会话状态，不落任何业务数据。"""
import json

import redis

from app.config.settings import settings

SLOTS_TTL_SECONDS = 3600


def _client() -> redis.Redis:
    return redis.Redis(
        host=settings.redis_host,
        port=settings.redis_port,
        password=settings.redis_password or None,
        decode_responses=True,
        socket_timeout=3,
    )


def _key(session_id: str) -> str:
    return "iw:%s:%s" % (settings.project, session_id)


def redis_ping() -> str:
    try:
        _client().ping()
        return "ok"
    except Exception:  # noqa: BLE001 健康检查须吞掉一切连接异常
        return "unreachable"


def load_slots(session_id: str) -> dict:
    raw = _client().get(_key(session_id))
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def save_slots(session_id: str, slots: dict) -> None:
    _client().set(_key(session_id), json.dumps(slots, ensure_ascii=False), ex=SLOTS_TTL_SECONDS)


def merge_slots(session_id: str, patch: dict) -> dict:
    slots = load_slots(session_id)
    slots.update(patch)
    save_slots(session_id, slots)
    return slots


def list_sessions() -> list[dict]:
    """枚举本项目全部会话槽位（scan 非 keys，不阻塞 Redis）；只读，不落业务数据。"""
    prefix = "iw:%s:" % settings.project
    client = _client()
    out = []
    for key in client.scan_iter(match=prefix + "*"):
        session_id = key[len(prefix):]
        out.append({"session_id": session_id, "slots": load_slots(session_id)})
    return out
