// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// 非实时交互：msgid 幂等合并 + 异步处理 + 文件回推。
//
// 契约（与设计文档第 8 节一致，三栈同形）：入站消息带 msgid 时按 msg:{session_id}:{msgid}
// 登记幂等记录，重发不重复处理；异步任务结果文件落盘 data/files/（默认本地实现，
// 可整层替换：SaveFile/LoadFile 即接口），Redis 只存 状态+文件标识 映射（带 TTL）；
// 取回凭 会话+msgid 双段键，严禁裸 msgid 全局键；配 IW_CALLBACK_URL 则完成时推送一次
// （尽力而为，失败不影响轮询取回；消费端按 msgid 幂等重放安全）。
package service

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"time"

	"icewright.local/{{artifact_id}}/config"
)

const (
	msgTTL       = 3600 * time.Second
	callbackTO   = 5 * time.Second
	filesDirName = "data/files"
)

var alnumOnly = regexp.MustCompile(`^[A-Za-z0-9]+$`)

// AsyncService 编排幂等回放与异步任务执行。
type AsyncService struct {
	sessions *SessionService
	chat     *ChatService
}

func NewAsyncService(chat *ChatService, sessions *SessionService) *AsyncService {
	return &AsyncService{chat: chat, sessions: sessions}
}

func msgSuffix(sessionID, msgid string) string {
	return "msg:" + sessionID + ":" + msgid
}

func newID() string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		// crypto/rand 失败属系统级故障，退化为时间戳仍保证唯一可用
		return hex.EncodeToString([]byte(time.Now().Format("20060102150405.000000000")))
	}
	return hex.EncodeToString(buf)
}

// AnswerIdempotent 是同步 /chat 的 msgid 支路：已处理过直接回放原回执（不重复处理）。
// Redis 登记失败只降级为“无幂等保护”，绝不影响同步应答本身。
func (a *AsyncService) AnswerIdempotent(sessionID, msgid, message, language string) Answer {
	if msgid == "" {
		return a.chat.Answer(sessionID, message, language)
	}
	if rec, ok := a.sessions.GetRecord(msgSuffix(sessionID, msgid)); ok {
		if rec["status"] == "ready" {
			var cached Answer
			if restamp, err := json.Marshal(rec["reply"]); err == nil && json.Unmarshal(restamp, &cached) == nil {
				return cached
			}
		}
	}
	result := a.chat.Answer(sessionID, message, language)
	_ = a.sessions.PutRecord(msgSuffix(sessionID, msgid), map[string]any{
		"status": "ready", "reply": result, "files": []any{},
	})
	return result
}

// AcceptAsync 受理异步请求：重复 msgid 幂等返回既有状态，不再投任务。
// msgid 为空由服务端生成（回执中返回）。
func (a *AsyncService) AcceptAsync(sessionID, msgid, message, language string) (string, string, error) {
	if msgid == "" {
		msgid = newID()
	}
	suffix := msgSuffix(sessionID, msgid)
	if rec, ok := a.sessions.GetRecord(suffix); ok {
		status, _ := rec["status"].(string)
		if status == "" {
			status = "accepted"
		}
		return msgid, status, nil
	}
	if err := a.sessions.PutRecord(suffix, map[string]any{
		"status": "accepted", "reply": nil, "files": []any{},
	}); err != nil {
		return msgid, "", err
	}
	go a.run(sessionID, msgid, message, language)
	return msgid, "accepted", nil
}

func (a *AsyncService) run(sessionID, msgid, message, language string) {
	result := a.chat.Answer(sessionID, message, language)
	fileID, err := SaveFile(map[string]any{
		"session_id": sessionID, "msgid": msgid, "reply": result.Reply,
		"matched_rules": result.MatchedRules, "language": result.Language,
	})
	if err != nil {
		// 异步任务失败必须落状态，绝不留悬挂 accepted
		_ = a.sessions.PutRecord(msgSuffix(sessionID, msgid), map[string]any{
			"status": "failed", "error": err.Error(), "files": []any{},
		})
		return
	}
	files := []any{map[string]any{"file_id": fileID, "name": "reply-" + msgid + ".json"}}
	_ = a.sessions.PutRecord(msgSuffix(sessionID, msgid), map[string]any{
		"status": "ready", "reply": result, "files": files,
	})
	pushCallback(sessionID, msgid, files)
}

func pushCallback(sessionID, msgid string, files []any) {
	if config.CallbackURL == "" {
		return
	}
	payload, err := json.Marshal(map[string]any{
		"session_id": sessionID, "msgid": msgid, "files": files,
	})
	if err != nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), callbackTO)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, config.CallbackURL, bytes.NewReader(payload))
	if err != nil {
		return
	}
	req.Header.Set("Content-Type", "application/json")
	if resp, err := http.DefaultClient.Do(req); err == nil {
		_ = resp.Body.Close()
	}
}

// FilesView 轮询视图：状态 + 可下载文件清单；msgid 未登记（或已过 TTL）返回 nil。
func (a *AsyncService) FilesView(sessionID, msgid string) map[string]any {
	rec, ok := a.sessions.GetRecord(msgSuffix(sessionID, msgid))
	if !ok {
		return nil
	}
	status, _ := rec["status"].(string)
	if status == "accepted" {
		status = "pending"
	}
	viewFiles := []any{}
	if raw, ok := rec["files"].([]any); ok {
		for _, item := range raw {
			f, ok := item.(map[string]any)
			if !ok {
				continue
			}
			f["download_url"] = "/messages/" + msgid + "/files/" + toStr(f["file_id"]) + "?session_id=" + sessionID
			viewFiles = append(viewFiles, f)
		}
	}
	return map[string]any{
		"session_id": sessionID, "msgid": msgid, "status": status, "files": viewFiles,
	}
}

func toStr(v any) string {
	s, _ := v.(string)
	return s
}

// SaveFile 结果文件落盘（默认实现=本地 data/files，换共享存储只改 SaveFile/LoadFile 这一层）。
func SaveFile(content map[string]any) (string, error) {
	fileID := newID()
	if err := os.MkdirAll(filesDirName, 0o755); err != nil {
		return "", err
	}
	payload, err := json.Marshal(content)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(filesDirName, fileID+".json"), payload, 0o644); err != nil {
		return "", err
	}
	return fileID, nil
}

// LoadFile 按服务端生成的 file_id 取文件路径；只认 .json 快照，杜绝路径穿越。
func LoadFile(fileID string) (string, bool) {
	if !alnumOnly.MatchString(fileID) {
		return "", false
	}
	path := filepath.Join(filesDirName, fileID+".json")
	if _, err := os.Stat(path); err != nil {
		return "", false
	}
	return path, true
}
