// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// 非实时交互契约测试：msgid 幂等、异步文件回推、会话+msgid 命名空间隔离。
//
// 依赖 Redis（与真实部署一致）；不可达则跳过，不误报失败。
package service

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func newAsync(t *testing.T) *AsyncService {
	t.Helper()
	sessions := NewSessionService()
	if sessions.RedisPing() != "ok" {
		t.Skip("Redis 不可达，异步契约测试跳过")
	}
	chat, err := NewChatService(sessions)
	if err != nil {
		t.Fatalf("规则装载失败: %v", err)
	}
	return NewAsyncService(chat, sessions)
}

// Redis 登记记录跨测试轮次存续，固定 msgid 会命中上轮缓存或上轮失败态——键必须带随机后缀。
func uid() string { return newID()[:8] }

func TestSameMsgidReplayIdentical(t *testing.T) {
	async := newAsync(t)
	session, msgid := "s-gdup-"+uid(), "m-gdup-"+uid()
	a1 := async.AnswerIdempotent(session, msgid, "理赔需要哪些材料", "zh")
	a2 := async.AnswerIdempotent(session, msgid, "理赔需要哪些材料", "zh")
	if a1.Reply != a2.Reply || a1.Language != a2.Language {
		t.Fatalf("重复 msgid 回执不一致: %+v vs %+v", a1, a2)
	}
	rec, ok := async.sessions.GetRecord(msgSuffix(session, msgid))
	if !ok || rec["status"] != "ready" {
		t.Fatalf("msgid 幂等登记缺失: %+v ok=%v", rec, ok)
	}
}

func TestAsyncRoundtripFilesAndDownload(t *testing.T) {
	async := newAsync(t)
	session, msgid := "s-gasync-"+uid(), "m-gasync-"+uid()
	gotID, status, err := async.AcceptAsync(session, msgid, "生成理赔材料包", "zh")
	if err != nil || gotID != msgid {
		t.Fatalf("受理失败: msgid=%q err=%v", gotID, err)
	}
	if status != "accepted" && status != "ready" && status != "failed" {
		t.Fatalf("未知受理状态: %q", status)
	}
	view := waitDone(t, async, session, msgid)
	if view["status"] != "ready" {
		t.Fatalf("异步任务未就绪: %v", view["status"])
	}
	files, _ := view["files"].([]any)
	if len(files) != 1 {
		t.Fatalf("结果文件应恰为 1 份，实际 %d", len(files))
	}
	fileID := files[0].(map[string]any)["file_id"].(string)
	path, ok := LoadFile(fileID)
	if !ok {
		t.Fatalf("结果文件不可下载: %s", fileID)
	}
	raw, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		t.Fatalf("读取结果文件失败: %v", err)
	}
	var payload map[string]any
	if err := json.Unmarshal(raw, &payload); err != nil {
		t.Fatalf("结果文件非法 JSON: %v", err)
	}
	if payload["msgid"] != msgid || payload["session_id"] != session {
		t.Fatalf("结果文件缺少会话/msgid 标识: %v", payload)
	}
}

func TestMsgidIsolatedBySessionNamespace(t *testing.T) {
	async := newAsync(t)
	sessionA, sessionB, msgid := "s-giso-a-"+uid(), "s-giso-b-"+uid(), "m-giso-"+uid()
	if _, _, err := async.AcceptAsync(sessionA, msgid, "甲会话消息", "zh"); err != nil {
		t.Fatalf("受理失败: %v", err)
	}
	if async.FilesView(sessionB, msgid) != nil {
		t.Fatal("裸 msgid 跨会话不得取回（命名空间隔离失效）")
	}
	if view := waitDone(t, async, sessionA, msgid); view == nil {
		t.Fatal("甲会话应能凭 会话+msgid 取回")
	}
}

func TestUnknownMsgidHasNoView(t *testing.T) {
	async := newAsync(t)
	if async.FilesView("s-gnone", "m-gnone") != nil {
		t.Fatal("未登记 msgid 不该有视图")
	}
}

func waitDone(t *testing.T, async *AsyncService, sessionID, msgid string) map[string]any {
	t.Helper()
	// 上限须大于模型兜底超时：未配置模型时异步任务在模型超时后仍会落 ready/failed，不该被误判悬挂
	deadline := time.Now().Add(40 * time.Second)
	for time.Now().Before(deadline) {
		view := async.FilesView(sessionID, msgid)
		if view == nil {
			t.Fatalf("登记记录不应消失")
		}
		status := view["status"]
		if status == "ready" || status == "failed" {
			return view
		}
		time.Sleep(50 * time.Millisecond)
	}
	t.Fatalf("异步任务未在 15s 内落状态")
	return nil
}
