// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package service 对话编排：确定性规则优先，规则未覆盖处才调用大模型，模型不可用则友好兜底。
//
// 模型调用走 CloudWeGo Eino 框架（eino-ext OpenAI-compatible ChatModel）；
// IW_MODEL_BASE_URL 传含 /v1 的根地址（如 https://api.deepseek.com/v1），密钥禁止出现在代码中。
package service

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/cloudwego/eino-ext/components/model/openai"
	"github.com/cloudwego/eino/schema"

	"icewright.local/{{artifact_id}}/config"
	"icewright.local/{{artifact_id}}/domain"
	"icewright.local/{{artifact_id}}/integration"
)

const llmTimeout = 30 * time.Second

// Answer 是 /chat 的响应体，线格式与 python/java 栈完全一致。
type Answer struct {
	SessionID    string   `json:"session_id"`
	Reply        string   `json:"reply"`
	MatchedRules []string `json:"matched_rules"`
	Language     string   `json:"language"`
}

// ChatService 持有会话存储与编译进项目的规则表。
type ChatService struct {
	sessions *SessionService
	rules    []domain.Rule
}

func NewChatService(sessions *SessionService) (*ChatService, error) {
	rules, err := domain.LoadRules()
	if err != nil {
		return nil, err
	}
	return &ChatService{sessions: sessions, rules: rules}, nil
}

func ruleID(rule domain.Rule) string {
	switch v := rule["id"].(type) {
	case string:
		return v
	case nil:
		return ""
	default:
		return fmt.Sprintf("%v", v)
	}
}

// callModel 走 Eino 的 OpenAI-compatible ChatModel；任何异常由调用方兜底为 model_unavailable。
func (c *ChatService) callModel(message string, injections []string, language string) (string, error) {
	bullets := "- 无附加规则"
	if len(injections) > 0 {
		lines := make([]string, 0, len(injections))
		for _, s := range injections {
			lines = append(lines, "- "+s)
		}
		bullets = strings.Join(lines, "\n")
	}
	system := fmt.Sprintf("你是客服系统「%s」，遵守以下行业规则要求作答：\n%s\n%s",
		config.Project, bullets, domain.T("model_language", language, nil))

	temperature := float32(0)
	chatModel, err := openai.NewChatModel(context.Background(), &openai.ChatModelConfig{
		BaseURL:     config.ModelBaseURL,
		APIKey:      config.ModelAPIKey,
		Model:       config.ModelName,
		Temperature: &temperature,
	})
	if err != nil {
		return "", fmt.Errorf("模型客户端构建失败: %w", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), llmTimeout)
	defer cancel()
	reply, err := chatModel.Generate(ctx, []*schema.Message{
		schema.SystemMessage(system),
		schema.UserMessage(message),
	})
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(reply.Content) == "" {
		return "", fmt.Errorf("模型响应缺少 choices[0].message.content")
	}
	return reply.Content, nil
}

// Answer 执行五级确定性管线：pre_validator → 禁语 → takeover → 决策 → 模型兜底。
func (c *ChatService) Answer(sessionID, message, language string) Answer {
	lang := domain.Normalize(language)
	slots := c.sessions.LoadSlots(sessionID)
	facts := domain.Fact{}
	for k, v := range slots {
		facts[k] = v
	}
	facts["last_message"] = message
	integration.Enrich(facts)

	matched := domain.MatchRules(c.rules, facts)
	matchedIDs := make([]string, 0, len(matched))
	for _, r := range matched {
		matchedIDs = append(matchedIDs, ruleID(r))
	}

	done := func(replyKey, id string) Answer {
		reply := domain.T(replyKey, lang, nil)
		if id != "" {
			reply = domain.T(replyKey, lang, map[string]string{"rule": id})
		}
		return Answer{SessionID: sessionID, Reply: reply, MatchedRules: matchedIDs, Language: lang}
	}

	// 1) 硬拦截：pre_validator 规则命中即挡下，绝不进模型
	for _, r := range matched {
		if r["enforcement_point"] == "pre_validator" {
			return done("pre_validator", ruleID(r))
		}
	}
	// 2) 禁语扫描：forbidden_pattern 直接匹配用户消息
	for _, r := range c.rules {
		if r["type"] == "forbidden_pattern" && domain.PatternHitsMessage(r, message) {
			return done("forbidden", ruleID(r))
		}
	}
	// 3) 升级/接管类：命中即转人工并给出规则依据（原因必须可追溯）
	for _, r := range matched {
		if r["enforcement_point"] == "takeover" {
			return done("takeover", ruleID(r))
		}
	}
	// 4) 决策规则：可确定性处置的不走模型
	for _, r := range matched {
		action := domain.DecisionFor(r)
		if action == nil {
			continue
		}
		kind, _ := action["kind"].(string)
		switch kind {
		case "transfer_human":
			return done("transfer", ruleID(r))
		case "set_slot":
			set, _ := action["set"].(map[string]any)
			if set == nil {
				set = map[string]any{}
			}
			merged, err := c.sessions.MergeSlots(sessionID, set)
			if err == nil {
				slots = merged
				for k, v := range merged {
					facts[k] = v
				}
			}
		}
	}

	reply, err := c.callModel(message, domain.CollectPromptInjections(c.rules), lang)
	if err != nil {
		reply = domain.T("model_unavailable", lang, nil)
	}

	turns := 0
	if f, ok := slots["turns"].(float64); ok {
		turns = int(f)
	}
	_, _ = c.sessions.MergeSlots(sessionID, map[string]any{"turns": turns + 1})
	return Answer{SessionID: sessionID, Reply: reply, MatchedRules: matchedIDs, Language: lang}
}
