// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// 身份隔离契约测试：验签语义、会话归属绑定、角色闸门（三栈同形，设计文档第 9 节）。
//
// 依赖 Redis（归属登记表与真实部署一致）；不可达则跳过，不误报失败。
package service

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"icewright.local/{{artifact_id}}/config"
)

func newIdentity(t *testing.T) *IdentityService {
	t.Helper()
	sessions := NewSessionService()
	if sessions.RedisPing() != "ok" {
		t.Skip("Redis 不可达，身份隔离测试跳过")
	}
	return NewIdentityService(sessions)
}

// withSecret 临时切换共享密钥，测试结束恢复（config.AuthSecret 是包级变量）。
func withSecret(t *testing.T, secret string) {
	t.Helper()
	old := config.AuthSecret
	config.AuthSecret = secret
	t.Cleanup(func() { config.AuthSecret = old })
}

func reqIdent(user, group, role, sign string) *http.Request {
	r := httptest.NewRequest(http.MethodPost, "/chat", nil)
	if user != "" {
		r.Header.Set("X-IW-User", user)
	}
	if group != "" {
		r.Header.Set("X-IW-Group", group)
	}
	if role != "" {
		r.Header.Set("X-IW-Role", role)
	}
	if sign != "" {
		r.Header.Set("X-IW-Sign", sign)
	}
	return r
}

func statusOf(t *testing.T, err error) int {
	t.Helper()
	if err == nil {
		t.Fatalf("期望错误，实际为 nil")
	}
	apiErr, ok := err.(*APIError)
	if !ok {
		t.Fatalf("错误未携带状态码: %v", err)
	}
	return apiErr.Status
}

func TestDevModeNoHeadersMeansLocalDeveloper(t *testing.T) {
	withSecret(t, "")
	ident, err := newIdentity(t).Identify(reqIdent("", "", "", ""))
	if err != nil {
		t.Fatalf("调试模式免签请求应通过: %v", err)
	}
	if ident.Role != "developer" || ident.Signed {
		t.Fatalf("调试模式无头应记名本机开发者: %+v", ident)
	}
}

func TestBadCharsetAndUnknownRoleRejected(t *testing.T) {
	withSecret(t, "")
	svc := newIdentity(t)
	if got := statusOf(t, mustErr(svc.Identify(reqIdent("bad user!", "g", "customer", "")))); got != http.StatusBadRequest {
		t.Fatalf("非法字符集应 400，实际 %d", got)
	}
	if got := statusOf(t, mustErr(svc.Identify(reqIdent("u", "g", "boss", "")))); got != http.StatusForbidden {
		t.Fatalf("未知用户类型应 403，实际 %d", got)
	}
}

func mustErr(_ Identity, err error) error { return err }

func TestSignedModeValidatesHmacAndRefusesMissing(t *testing.T) {
	withSecret(t, "test-secret-"+uid())
	svc := newIdentity(t)
	good := Sign("alice", "ga", "customer")
	if ident, err := svc.Identify(reqIdent("alice", "ga", "customer", good)); err != nil || !ident.Signed {
		t.Fatalf("合法签名应通过且记为已验签: %+v err=%v", ident, err)
	}
	if got := statusOf(t, mustErr(svc.Identify(reqIdent("alice", "ga", "customer", good+"deadbeef")))); got != http.StatusUnauthorized {
		t.Fatalf("篡改签名应 401，实际 %d", got)
	}
	if got := statusOf(t, mustErr(svc.Identify(reqIdent("alice", "ga", "customer", "")))); got != http.StatusUnauthorized {
		t.Fatalf("缺签名应 401，实际 %d", got)
	}
	if got := statusOf(t, mustErr(svc.Identify(reqIdent("", "", "", "")))); got != http.StatusUnauthorized {
		t.Fatalf("生产模式无身份头应 401，实际 %d", got)
	}
}

func TestSessionOwnershipBindingAndViews(t *testing.T) {
	withSecret(t, "")
	svc := newIdentity(t)
	alice := Identity{User: "alice-" + uid(), Group: "ga", Role: "customer"}
	bob := Identity{User: "alice-x-" + uid(), Group: "ga", Role: "customer"}
	otherGroup := Identity{User: alice.User, Group: "gb-" + uid(), Role: "customer"}
	dev := Identity{User: "dev-" + uid(), Group: "default", Role: "developer"}

	session := "s-bind-" + uid()
	// 未登记会话：只读放行（新会话），首用即绑定
	if err := svc.Viewable(bob, session); err != nil {
		t.Fatalf("未登记会话只读应放行: %v", err)
	}
	if err := svc.EnsureSession(alice, session); err != nil {
		t.Fatalf("首用绑定失败: %v", err)
	}
	if err := svc.EnsureSession(bob, session); statusOf(t, err) != http.StatusForbidden {
		t.Fatalf("他人会话应 403: %v", err)
	}
	if err := svc.EnsureSession(otherGroup, session); statusOf(t, err) != http.StatusForbidden {
		t.Fatalf("同用户跨组应 403（组隔离）: %v", err)
	}
	if err := svc.EnsureSession(dev, session); err != nil {
		t.Fatalf("developer 应放行: %v", err)
	}
	if err := svc.Viewable(alice, session); err != nil {
		t.Fatalf("所有者只读应放行: %v", err)
	}
	if err := svc.Viewable(bob, session); statusOf(t, err) != http.StatusForbidden {
		t.Fatalf("非所有者只读应 403: %v", err)
	}
	// 活跃续期：重复 EnsureSession 不改变归属
	if err := svc.EnsureSession(alice, session); err != nil {
		t.Fatalf("所有者活跃续期失败: %v", err)
	}
	owner, ok := svc.sessions.GetRecord(ownerPrefix + session)
	if !ok || owner["user"] != alice.User || owner["group"] != alice.Group {
		t.Fatalf("归属登记被篡改: %+v ok=%v", owner, ok)
	}
}

func TestRequireRoleGate(t *testing.T) {
	customer := Identity{User: "u", Group: "g", Role: "customer"}
	if err := RequireRole(customer, "developer", "agent"); statusOf(t, err) != http.StatusForbidden {
		t.Fatalf("customer 走 developer/agent 闸门应 403: %v", err)
	}
	if err := RequireRole(customer, "customer"); err != nil {
		t.Fatalf("customer 走 customer 闸门应放行: %v", err)
	}
}
