// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// 身份与隔离：组 / 会话 / 用户 / 用户类型四层隔离的框架层实现（三栈同形契约，设计文档第 9 节）。
//
// 默认实现=客户网关注入 X-IW-User / X-IW-Group / X-IW-Role 头 + HMAC-SHA256 共享密钥验签
// （IW_AUTH_SECRET）；客户已有统一认证体系时只替换 Identify 一个方法，业务代码不动。
// 权限闸门收口在 HTTP 层，不依赖模型自觉。
package service

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"regexp"
	"strings"

	"icewright.local/{{artifact_id}}/config"
)

// Identity 是身份四元组；Signed=是否经共享密钥验签。
type Identity struct {
	User   string
	Group  string
	Role   string
	Signed bool
}

// Roles 是允许的用户类型全集：developer（开发/测试）、agent（对方系统业务员）、customer（对方系统用户）。
var Roles = []string{"developer", "agent", "customer"}

// APIError 携带 HTTP 状态码的分层错误，web 层按 Status 编码 {detail}。
type APIError struct {
	Status int
	Detail string
}

func (e *APIError) Error() string { return e.Detail }

var identityIDPattern = regexp.MustCompile(`^[A-Za-z0-9_.:-]{1,128}$`)

const ownerPrefix = "sess:"

// IdentityService 依赖会话存储做归属登记（sess: 键，带 TTL，不落长期数据）。
type IdentityService struct {
	sessions *SessionService
}

func NewIdentityService(sessions *SessionService) *IdentityService {
	return &IdentityService{sessions: sessions}
}

// DevMode 未配置共享密钥即调试模式：免签、无头请求记名本机开发者（开发后台明文告警）。
func DevMode() bool { return config.AuthSecret == "" }

// Sign 是 X-IW-Sign 计算口径：HMAC-SHA256(secret, "user|group|role") 十六进制小写（三栈一致）。
func Sign(user, group, role string) string {
	mac := hmac.New(sha256.New, []byte(config.AuthSecret))
	mac.Write([]byte(user + "|" + group + "|" + role))
	return hex.EncodeToString(mac.Sum(nil))
}

// Identify 解析并校验身份请求头：验签失败 401，角色非法 403，标识字符集非法 400。
//
// 调试模式（未配 IW_AUTH_SECRET）下不带任何头=本机开发者，直连后台页面可用；
// 一旦配置密钥，所有请求都必须带签名头——生产环境无免签通道。
func (i *IdentityService) Identify(r *http.Request) (Identity, error) {
	user := r.Header.Get("X-IW-User")
	group := r.Header.Get("X-IW-Group")
	role := r.Header.Get("X-IW-Role")
	if user == "" && group == "" && role == "" {
		if !DevMode() {
			return Identity{}, &APIError{http.StatusUnauthorized, "缺少身份请求头（X-IW-User/X-IW-Group/X-IW-Role）"}
		}
		return Identity{User: "dev-local", Group: "default", Role: "developer", Signed: false}, nil
	}
	if !identityIDPattern.MatchString(user) || !identityIDPattern.MatchString(group) {
		return Identity{}, &APIError{http.StatusBadRequest, "user/group 标识字符集非法"}
	}
	if !validRole(role) {
		return Identity{}, &APIError{http.StatusForbidden, "用户类型不在允许集合: " + role}
	}
	if !DevMode() {
		mac := r.Header.Get("X-IW-Sign")
		if !hmac.Equal([]byte(Sign(user, group, role)), []byte(mac)) {
			return Identity{}, &APIError{http.StatusUnauthorized, "签名校验失败（X-IW-Sign 与共享密钥不符）"}
		}
	}
	return Identity{User: user, Group: group, Role: role, Signed: !DevMode()}, nil
}

// EnsureSession 会话首用绑定 用户+组；此后仅所有者或 developer 可用（活跃即续期）。
func (i *IdentityService) EnsureSession(ident Identity, sessionID string) error {
	owner, ok := i.sessions.GetRecord(ownerPrefix + sessionID)
	if !ok {
		return i.sessions.PutRecord(ownerPrefix+sessionID, map[string]any{
			"user": ident.User, "group": ident.Group,
		})
	}
	if err := assertOwned(ident, owner); err != nil {
		return err
	}
	return i.sessions.PutRecord(ownerPrefix+sessionID, owner)
}

// Viewable 只读校验（不登记归属）：developer 全量可见，其余须与登记所有者同用户同组。
func (i *IdentityService) Viewable(ident Identity, sessionID string) error {
	owner, ok := i.sessions.GetRecord(ownerPrefix + sessionID)
	if !ok {
		return nil
	}
	return assertOwned(ident, owner)
}

// RequireRole 角色闸门：不在允许集合内即 403。
func RequireRole(ident Identity, roles ...string) error {
	for _, role := range roles {
		if ident.Role == role {
			return nil
		}
	}
	return &APIError{http.StatusForbidden,
		"该端点仅限 " + strings.Join(roles, "/") + "，当前用户类型: " + ident.Role}
}

func assertOwned(ident Identity, owner map[string]any) error {
	if ident.Role == "developer" {
		return nil
	}
	if owner["user"] != ident.User || owner["group"] != ident.Group {
		return &APIError{http.StatusForbidden, "会话归属其他用户或组（会话/用户/组隔离生效）"}
	}
	return nil
}

func validRole(role string) bool {
	for _, r := range Roles {
		if role == r {
			return true
		}
	}
	return false
}
