// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package service 会话槽位存储：Redis 只存易失会话状态，不落任何业务数据。
package service

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"

	"icewright.local/{{artifact_id}}/config"
	"icewright.local/{{artifact_id}}/domain"
)

const slotsTTL = 3600 * time.Second
const dialTimeout = 3 * time.Second

// SessionService 封装会话槽位的读写与合并。
type SessionService struct {
	rdb *redis.Client
}

func NewSessionService() *SessionService {
	return &SessionService{
		rdb: redis.NewClient(&redis.Options{
			Addr:         fmt.Sprintf("%s:%d", config.RedisHost, config.RedisPort),
			Password:     config.RedisPassword,
			DialTimeout:  dialTimeout,
			ReadTimeout:  dialTimeout,
			WriteTimeout: dialTimeout,
		}),
	}
}

func (s *SessionService) key(sessionID string) string {
	return fmt.Sprintf("iw:%s:%s", config.Project, sessionID)
}

// RedisPing 健康检查吞掉一切连接异常。
func (s *SessionService) RedisPing() string {
	ctx, cancel := context.WithTimeout(context.Background(), dialTimeout)
	defer cancel()
	if err := s.rdb.Ping(ctx).Err(); err != nil {
		return "unreachable"
	}
	return "ok"
}

func (s *SessionService) LoadSlots(sessionID string) domain.Fact {
	ctx, cancel := context.WithTimeout(context.Background(), dialTimeout)
	defer cancel()
	raw, err := s.rdb.Get(ctx, s.key(sessionID)).Result()
	if err != nil || raw == "" {
		return domain.Fact{}
	}
	var data domain.Fact
	if err := json.Unmarshal([]byte(raw), &data); err != nil {
		return domain.Fact{}
	}
	return data
}

func (s *SessionService) SaveSlots(sessionID string, slots domain.Fact) error {
	ctx, cancel := context.WithTimeout(context.Background(), dialTimeout)
	defer cancel()
	payload, err := json.Marshal(slots)
	if err != nil {
		return fmt.Errorf("槽位序列化失败: %w", err)
	}
	return s.rdb.Set(ctx, s.key(sessionID), payload, slotsTTL).Err()
}

func (s *SessionService) MergeSlots(sessionID string, patch map[string]any) (domain.Fact, error) {
	slots := s.LoadSlots(sessionID)
	for k, v := range patch {
		slots[k] = v
	}
	if err := s.SaveSlots(sessionID, slots); err != nil {
		return nil, err
	}
	return slots, nil
}
