// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package integration 对接客户核心系统：本系统不落业务数据，事实一律实时取数。
package integration

import (
	"database/sql"
	"fmt"
	"sort"
	"strings"

	_ "github.com/go-sql-driver/mysql"

	"icewright.local/{{artifact_id}}/config"
	"icewright.local/{{artifact_id}}/domain"
)

var mockClaims = map[string]domain.Fact{
	"CLM-0001": {"claim_status": "approved", "claim_amount": 3200.0, "claim_type": "vehicle_damage"},
	"CLM-0002": {"claim_status": "pending", "claim_amount": 800.0, "claim_type": "third_party"},
}

const claimSQL = "SELECT status AS claim_status, amount AS claim_amount, type AS claim_type " +
	"FROM claims WHERE claim_id = ?"

// FetchClaim mock 模式返回内置示例；mysql 模式只读查询对方核心系统表。
func FetchClaim(claimID string) domain.Fact {
	if config.CoreMode == "mock" {
		copied := domain.Fact{}
		for k, v := range mockClaims[claimID] {
			copied[k] = v
		}
		return copied
	}
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?timeout=3s&readTimeout=3s",
		config.MysqlUser, config.MysqlPassword, config.MysqlHost, config.MysqlPort, config.MysqlDatabase)
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return domain.Fact{}
	}
	defer db.Close()
	row := db.QueryRow(claimSQL, claimID)
	var (
		status string
		amount float64
		ctype  string
	)
	if err := row.Scan(&status, &amount, &ctype); err != nil {
		return domain.Fact{}
	}
	return domain.Fact{"claim_status": status, "claim_amount": amount, "claim_type": ctype}
}

// Enrich 若会话里出现工单号，把核心系统实时字段并入事实集供规则匹配。
func Enrich(facts domain.Fact) domain.Fact {
	claimID := ""
	if v, ok := facts["claim_id"].(string); ok && v != "" {
		claimID = v
	} else if v, ok := facts["last_message"].(string); ok {
		claimID = v
	}
	if config.CoreMode == "mock" {
		known := make([]string, 0, len(mockClaims))
		for id := range mockClaims {
			known = append(known, id)
		}
		sort.Strings(known) // map 遍历无序，显式排序保证与 python 栈同款确定性
		for _, id := range known {
			if strings.Contains(claimID, id) {
				facts["claim_id"] = id
				break
			}
		}
	}
	if id, ok := facts["claim_id"].(string); ok && id != "" {
		for k, v := range FetchClaim(id) {
			facts[k] = v
		}
	}
	return facts
}
