# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会覆盖本文件（加 ICEWRIGHT-CUSTOM 标记可跳过）
"""HTTP 层：入参校验与响应模型，业务逻辑一律下沉到 service。"""
from pathlib import Path
from typing import Literal

from fastapi import APIRouter
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from app.config.settings import settings
from app.domain import i18n
from app.service import chat as chat_service
from app.service import session as session_service

router = APIRouter()

STATIC_DIR = Path(__file__).resolve().parents[2] / "static"


class ChatRequest(BaseModel):
    session_id: str = Field(min_length=1, max_length=128)
    message: str = Field(min_length=1, max_length=4000)
    language: Literal["zh", "en"] = "zh"


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    matched_rules: list[str]
    language: str


class HealthResponse(BaseModel):
    project: str
    pack_ref: str
    redis: str
    languages: list[str]


@router.get("/", include_in_schema=False)
def home() -> FileResponse:
    return FileResponse(STATIC_DIR / "chat.html")


@router.get("/healthz", response_model=HealthResponse)
def healthz() -> HealthResponse:
    return HealthResponse(
        project=settings.project,
        pack_ref=settings.pack_ref,
        redis=session_service.redis_ping(),
        languages=sorted(i18n.MESSAGES),
    )


@router.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    return ChatResponse(**chat_service.answer(req.session_id, req.message, req.language))
