# AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
"""HTTP 层：入参校验与响应模型，业务逻辑一律下沉到 service。

页面矩阵：/ 调试聊天页（必含）、/admin 开发后台（必含，只读契约与运行态）、
/console 业务人员后台（workspace.business_console=true 时生成，否则 404）。
"""
import json
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from app.config.settings import settings
from app.domain import i18n
from app.domain import rules as rule_engine
from app.service import asyncmsg
from app.service import session as session_service

router = APIRouter()

STATIC_DIR = Path(__file__).resolve().parents[2] / "static"
DATA_DIR = Path(__file__).resolve().parents[1] / "data"

# msgid 字符集收紧：安全进 Redis 键与 URL，跨栈一致（= java @Pattern / go 校验）
_MSGID_PATTERN = r"^[A-Za-z0-9_.:-]{1,128}$"


class ChatRequest(BaseModel):
    session_id: str = Field(min_length=1, max_length=128)
    message: str = Field(min_length=1, max_length=4000)
    language: Literal["zh", "en"] = "zh"
    msgid: str | None = Field(default=None, pattern=_MSGID_PATTERN)


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    matched_rules: list[str]
    language: str


class HealthResponse(BaseModel):
    project: str
    pack_ref: str
    redis: str
    languages: list[str]


@router.get("/", include_in_schema=False)
def home() -> FileResponse:
    return FileResponse(STATIC_DIR / "chat.html")


@router.get("/healthz", response_model=HealthResponse)
def healthz() -> HealthResponse:
    return HealthResponse(
        project=settings.project,
        pack_ref=settings.pack_ref,
        redis=session_service.redis_ping(),
        languages=sorted(i18n.MESSAGES),
    )


@router.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    """同步对话；带 msgid 时幂等——同会话重复 msgid 回放原回执，不重复处理。"""
    result = asyncmsg.answer_idempotent(
        req.session_id, req.msgid or "", req.message, req.language
    )
    return ChatResponse(**result)


@router.post("/chat/async", status_code=202)
def chat_async(req: ChatRequest) -> dict[str, str]:
    """异步受理（非实时交互入口）：立即回执 accepted，后台线程处理完写结果文件。

    msgid 缺省由服务端生成；重复提交同 msgid 幂等返回既有状态，不会二次处理。
    """
    msgid, status = asyncmsg.accept_async(req.session_id, req.msgid or "", req.message, req.language)
    return {"session_id": req.session_id, "msgid": msgid, "status": status}


@router.get("/messages/{msgid}/files")
def message_files(msgid: str, session_id: str = "") -> dict[str, Any]:
    """轮询取回：凭 会话+msgid 双段键查状态与文件清单（严禁裸 msgid 全局取回）。"""
    if not session_id:
        raise HTTPException(status_code=400, detail="必须携带 session_id（命名空间隔离）")
    view = asyncmsg.files_view(session_id, msgid)
    if view is None:
        raise HTTPException(status_code=404, detail="msgid 未登记或已过 TTL，请重新提交")
    return view


@router.get("/messages/{msgid}/files/{file_id}")
def message_file(msgid: str, file_id: str, session_id: str = "") -> FileResponse:
    """下载异步结果文件：file_id 须在该 会话+msgid 登记表内（服务端生成，防越权枚举）。"""
    view = message_files(msgid, session_id)
    if not any(f["file_id"] == file_id for f in view["files"]):
        raise HTTPException(status_code=404, detail="file_id 不在该会话登记内")
    path = asyncmsg.load_file(file_id)
    if path is None:
        raise HTTPException(status_code=404, detail="结果文件已被清理")
    return FileResponse(path, media_type="application/json")


def _read_data_json(name: str) -> list[dict]:
    path = DATA_DIR / name
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    key = name.removesuffix(".json")
    rows = payload.get(key, []) if isinstance(payload, dict) else payload
    return [r for r in rows if isinstance(r, dict)]


@router.get("/sessions/{session_id}")
def session_detail(session_id: str) -> dict[str, Any]:
    """会话槽位回显（调试页用）：只读 Redis 中的易失状态，不含业务数据。"""
    return {"session_id": session_id, "slots": session_service.load_slots(session_id)}


@router.get("/admin", include_in_schema=False)
def admin() -> FileResponse:
    return FileResponse(STATIC_DIR / "admin.html")


@router.get("/admin/overview")
def admin_overview() -> dict[str, Any]:
    """开发后台只读总览：运行态 + 规则/技能/接口契约（编译进项目的数据文件）。"""
    return {
        "project": settings.project,
        "pack_ref": settings.pack_ref,
        "redis": session_service.redis_ping(),
        "languages": sorted(i18n.MESSAGES),
        "model_configured": bool(
            settings.model_base_url and settings.model_name and settings.model_api_key
        ),
        "core_mode": settings.core_mode,
        "business_console": settings.business_console,
        "rules": rule_engine.load_rules(),
        "skills": _read_data_json("skills.json"),
        "apis": _read_data_json("apis.json"),
    }


def _require_console() -> None:
    if not settings.business_console:
        raise HTTPException(status_code=404, detail="业务后台未开启")


@router.get("/console", include_in_schema=False)
def console() -> FileResponse:
    _require_console()
    return FileResponse(STATIC_DIR / "console.html")


@router.get("/console/sessions")
def console_sessions() -> list[dict[str, Any]]:
    """业务后台会话列表：仅返回被规则打标的会话（session_id + 规则 id + 轮数）。"""
    _require_console()
    rows = []
    for item in session_service.list_sessions():
        slots = item["slots"]
        if slots.get("flagged"):
            rows.append(
                {
                    "session_id": item["session_id"],
                    "flagged": slots["flagged"],
                    "turns": slots.get("turns", 0),
                }
            )
    return rows
