// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"

	"icewright.local/{{artifact_id}}/service"
	"icewright.local/{{artifact_id}}/web"
)

//go:embed static/index.html static/admin.html static/console.html
var staticFS embed.FS

const listenAddr = ":8000"

func main() {
	index, err := fs.ReadFile(staticFS, "static/index.html")
	if err != nil {
		log.Fatalf("静态页面缺失: %v", err)
	}
	admin, err := fs.ReadFile(staticFS, "static/admin.html")
	if err != nil {
		log.Fatalf("开发后台页缺失: %v", err)
	}
	console, err := fs.ReadFile(staticFS, "static/console.html")
	if err != nil {
		log.Fatalf("业务后台页缺失: %v", err)
	}
	sessions := service.NewSessionService()
	chat, err := service.NewChatService(sessions)
	if err != nil {
		log.Fatalf("规则装载失败: %v", err)
	}
	async := service.NewAsyncService(chat, sessions)
	identity := service.NewIdentityService(sessions)
	handlers := web.NewHandlers(chat, async, sessions, identity, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write(index)
	}, admin, console)

	mux := http.NewServeMux()
	mux.HandleFunc("/chat", handlers.Chat)
	mux.HandleFunc("/chat/async", handlers.ChatAsync)
	mux.HandleFunc("/messages/", handlers.Messages)
	mux.HandleFunc("/healthz", handlers.Healthz)
	mux.HandleFunc("/admin", handlers.Admin)
	mux.HandleFunc("/admin/overview", handlers.AdminOverview)
	mux.HandleFunc("/console", handlers.Console)
	mux.HandleFunc("/console/sessions", handlers.ConsoleSessions)
	mux.HandleFunc("/sessions/", handlers.SessionDetail)
	mux.HandleFunc("/", handlers.Home)

	log.Printf("listening on %s", listenAddr)
	if err := http.ListenAndServe(listenAddr, mux); err != nil {
		log.Fatal(err)
	}
}
