// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package web 是 HTTP 层：入参校验与响应编码，业务逻辑一律下沉到 service。
package web

import (
	"encoding/json"
	"io"
	"net/http"
	"regexp"
	"strings"

	"icewright.local/{{artifact_id}}/config"
	"icewright.local/{{artifact_id}}/domain"
	"icewright.local/{{artifact_id}}/service"
)

const (
	maxSessionIDLen = 128
	maxMessageLen   = 4000
	maxBodyBytes    = 1 << 20
)

// validMsgid 字符集收紧：安全进 Redis 键与 URL，三栈一致。
var validMsgid = regexp.MustCompile(`^[A-Za-z0-9_.:-]{1,128}$`)

type chatRequest struct {
	SessionID string `json:"session_id"`
	Message   string `json:"message"`
	Language  string `json:"language"`
	MsgID     string `json:"msgid,omitempty"`
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, detail string) {
	writeJSON(w, http.StatusBadRequest, map[string]string{"detail": detail})
}

// Handlers 聚合页面矩阵与只读查询路由：GET /、/admin、/admin/overview、
// /sessions/{id}、/healthz、POST /chat；/console 与 /console/sessions 按开关守卫。
type Handlers struct {
	chat        *service.ChatService
	async       *service.AsyncService
	sessions    *service.SessionService
	indexHTML   func(w http.ResponseWriter, r *http.Request)
	adminHTML   []byte
	consoleHTML []byte
}

func NewHandlers(chat *service.ChatService, async *service.AsyncService, sessions *service.SessionService,
	indexHTML func(http.ResponseWriter, *http.Request), adminHTML, consoleHTML []byte) *Handlers {
	return &Handlers{chat: chat, async: async, sessions: sessions, indexHTML: indexHTML,
		adminHTML: adminHTML, consoleHTML: consoleHTML}
}

func (h *Handlers) Chat(w http.ResponseWriter, r *http.Request) {
	req, lang, ok := parseChat(w, r)
	if !ok {
		return
	}
	// 带 msgid 幂等：同会话重复 msgid 回放原回执，不重复处理
	writeJSON(w, http.StatusOK, h.async.AnswerIdempotent(req.SessionID, req.MsgID, req.Message, lang))
}

// parseChat 复用 /chat 的入参校验（/chat/async 线格式完全一致）。
func parseChat(w http.ResponseWriter, r *http.Request) (chatRequest, string, bool) {
	if r.Method != http.MethodPost {
		writeError(w, "仅支持 POST")
		return chatRequest{}, "", false
	}
	raw, err := io.ReadAll(io.LimitReader(r.Body, maxBodyBytes))
	if err != nil {
		writeError(w, "请求体读取失败")
		return chatRequest{}, "", false
	}
	var req chatRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		writeError(w, "请求体不是合法 JSON（字段：session_id/message/language/msgid）")
		return chatRequest{}, "", false
	}
	if req.SessionID == "" || len([]rune(req.SessionID)) > maxSessionIDLen {
		writeError(w, "session_id 必须非空且不超过 128 字符")
		return chatRequest{}, "", false
	}
	if req.Message == "" || len([]rune(req.Message)) > maxMessageLen {
		writeError(w, "message 必须非空且不超过 4000 字符")
		return chatRequest{}, "", false
	}
	lang := strings.ToLower(strings.TrimSpace(req.Language))
	if lang == "" {
		lang = domain.DefaultLanguage
	}
	if lang != "zh" && lang != "en" {
		writeError(w, "language 仅支持 zh/en")
		return chatRequest{}, "", false
	}
	if req.MsgID != "" && !validMsgid.MatchString(req.MsgID) {
		writeError(w, "msgid 仅允许字母/数字/._:-，长度 1~128")
		return chatRequest{}, "", false
	}
	return req, lang, true
}

// ChatAsync 异步受理：202 回执 accepted，后台 goroutine 处理完写结果文件；
// msgid 缺省由服务端生成，重复提交同 msgid 幂等返回既有状态。
func (h *Handlers) ChatAsync(w http.ResponseWriter, r *http.Request) {
	req, lang, ok := parseChat(w, r)
	if !ok {
		return
	}
	msgid, status, err := h.async.AcceptAsync(req.SessionID, req.MsgID, req.Message, lang)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	writeJSON(w, http.StatusAccepted, map[string]string{
		"session_id": req.SessionID, "msgid": msgid, "status": status,
	})
}

// Messages 处理 /messages/{msgid}/files 与 /messages/{msgid}/files/{file_id}：
// 轮询取回凭 会话+msgid 双段键（严禁裸 msgid 全局取回），下载 file_id 须在登记内。
func (h *Handlers) Messages(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, "仅支持 GET")
		return
	}
	sessionID := r.URL.Query().Get("session_id")
	if sessionID == "" {
		writeError(w, "必须携带 session_id（命名空间隔离）")
		return
	}
	rest := strings.TrimPrefix(r.URL.Path, "/messages/")
	parts := strings.Split(rest, "/")
	switch {
	case len(parts) == 2 && parts[1] == "files":
		view := h.async.FilesView(sessionID, parts[0])
		if view == nil {
			writeJSON(w, http.StatusNotFound, map[string]string{"detail": "msgid 未登记或已过 TTL，请重新提交"})
			return
		}
		writeJSON(w, http.StatusOK, view)
	case len(parts) == 3 && parts[1] == "files":
		view := h.async.FilesView(sessionID, parts[0])
		if view == nil {
			writeJSON(w, http.StatusNotFound, map[string]string{"detail": "msgid 未登记或已过 TTL，请重新提交"})
			return
		}
		if !fileRegistered(view, parts[2]) {
			writeJSON(w, http.StatusNotFound, map[string]string{"detail": "file_id 不在该会话登记内"})
			return
		}
		path, ok := service.LoadFile(parts[2])
		if !ok {
			writeJSON(w, http.StatusNotFound, map[string]string{"detail": "结果文件已被清理"})
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		http.ServeFile(w, r, path)
	default:
		writeJSON(w, http.StatusNotFound, map[string]string{"detail": "路径应为 /messages/{msgid}/files[/{file_id}]"})
	}
}

func fileRegistered(view map[string]any, fileID string) bool {
	raw, _ := view["files"].([]any)
	for _, item := range raw {
		f, _ := item.(map[string]any)
		if f["file_id"] == fileID {
			return true
		}
	}
	return false
}

func (h *Handlers) Healthz(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"project":   config.Project,
		"pack_ref":  config.PackRef,
		"redis":     h.sessions.RedisPing(),
		"languages": domain.Languages(),
	})
}

func (h *Handlers) Home(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, "仅支持 GET")
		return
	}
	h.indexHTML(w, r)
}

func writeHTML(w http.ResponseWriter, page []byte) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write(page)
}

// Admin 开发后台页（必含，只读）。
func (h *Handlers) Admin(w http.ResponseWriter, r *http.Request) {
	writeHTML(w, h.adminHTML)
}

// Console 业务人员后台页：开关未开启时 404，与 python/java 栈一致。
func (h *Handlers) Console(w http.ResponseWriter, r *http.Request) {
	if !config.BusinessConsole {
		writeJSON(w, http.StatusNotFound, map[string]string{"detail": "业务后台未开启"})
		return
	}
	writeHTML(w, h.consoleHTML)
}

// SessionDetail GET /sessions/{id}：调试页槽位回显，只读 Redis 易失状态。
func (h *Handlers) SessionDetail(w http.ResponseWriter, r *http.Request) {
	sessionID := strings.TrimPrefix(r.URL.Path, "/sessions/")
	if sessionID == "" || sessionID == r.URL.Path {
		writeError(w, "路径应为 /sessions/{session_id}")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"session_id": sessionID,
		"slots":      h.sessions.LoadSlots(sessionID),
	})
}

type adminOverviewBody struct {
	Project         string               `json:"project"`
	PackRef         string               `json:"pack_ref"`
	Redis           string               `json:"redis"`
	Languages       []string             `json:"languages"`
	ModelConfigured bool                 `json:"model_configured"`
	CoreMode        string               `json:"core_mode"`
	BusinessConsole bool                 `json:"business_console"`
	Rules           []domain.Rule        `json:"rules"`
	Skills          []domain.Skill       `json:"skills"`
	APIs            []domain.APIContract `json:"apis"`
}

// AdminOverview 开发后台总览：运行态 + 规则/技能/接口契约（编译进项目的数据文件）。
func (h *Handlers) AdminOverview(w http.ResponseWriter, r *http.Request) {
	rules, err := domain.LoadRules()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	skills, err := domain.LoadSkills()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	apis, err := domain.LoadAPIs()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	if rules == nil {
		rules = []domain.Rule{}
	}
	if skills == nil {
		skills = []domain.Skill{}
	}
	if apis == nil {
		apis = []domain.APIContract{}
	}
	writeJSON(w, http.StatusOK, adminOverviewBody{
		Project:         config.Project,
		PackRef:         config.PackRef,
		Redis:           h.sessions.RedisPing(),
		Languages:       domain.Languages(),
		ModelConfigured: config.ModelBaseURL != "" && config.ModelName != "" && config.ModelAPIKey != "",
		CoreMode:        config.CoreMode,
		BusinessConsole: config.BusinessConsole,
		Rules:           rules,
		Skills:          skills,
		APIs:            apis,
	})
}

type consoleSessionRow struct {
	SessionID string `json:"session_id"`
	Flagged   string `json:"flagged"`
	Turns     any    `json:"turns"`
}

// ConsoleSessions 业务后台待关注会话列表：仅规则打标的会话。
func (h *Handlers) ConsoleSessions(w http.ResponseWriter, r *http.Request) {
	if !config.BusinessConsole {
		writeJSON(w, http.StatusNotFound, map[string]string{"detail": "业务后台未开启"})
		return
	}
	rows := make([]consoleSessionRow, 0)
	for _, item := range h.sessions.ListSessions() {
		flagged, _ := item.Slots["flagged"].(string)
		if flagged == "" {
			continue
		}
		turns := item.Slots["turns"]
		if turns == nil {
			turns = 0
		}
		rows = append(rows, consoleSessionRow{SessionID: item.SessionID, Flagged: flagged, Turns: turns})
	}
	writeJSON(w, http.StatusOK, rows)
}
