// AUTO-GENERATED BY IceWright {{engine_version}} · 重生成会检测本地修改而非静默覆盖（加 ICEWRIGHT-CUSTOM 标记则完全交给定制层）
// Package web 是 HTTP 层：入参校验与响应编码，业务逻辑一律下沉到 service。
package web

import (
	"encoding/json"
	"io"
	"net/http"
	"strings"

	"icewright.local/{{artifact_id}}/config"
	"icewright.local/{{artifact_id}}/domain"
	"icewright.local/{{artifact_id}}/service"
)

const (
	maxSessionIDLen = 128
	maxMessageLen   = 4000
	maxBodyBytes    = 1 << 20
)

type chatRequest struct {
	SessionID string `json:"session_id"`
	Message   string `json:"message"`
	Language  string `json:"language"`
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, detail string) {
	writeJSON(w, http.StatusBadRequest, map[string]string{"detail": detail})
}

// Handlers 聚合页面矩阵与只读查询路由：GET /、/admin、/admin/overview、
// /sessions/{id}、/healthz、POST /chat；/console 与 /console/sessions 按开关守卫。
type Handlers struct {
	chat        *service.ChatService
	sessions    *service.SessionService
	indexHTML   func(w http.ResponseWriter, r *http.Request)
	adminHTML   []byte
	consoleHTML []byte
}

func NewHandlers(chat *service.ChatService, sessions *service.SessionService,
	indexHTML func(http.ResponseWriter, *http.Request), adminHTML, consoleHTML []byte) *Handlers {
	return &Handlers{chat: chat, sessions: sessions, indexHTML: indexHTML,
		adminHTML: adminHTML, consoleHTML: consoleHTML}
}

func (h *Handlers) Chat(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeError(w, "仅支持 POST")
		return
	}
	raw, err := io.ReadAll(io.LimitReader(r.Body, maxBodyBytes))
	if err != nil {
		writeError(w, "请求体读取失败")
		return
	}
	var req chatRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		writeError(w, "请求体不是合法 JSON（字段：session_id/message/language）")
		return
	}
	if req.SessionID == "" || len([]rune(req.SessionID)) > maxSessionIDLen {
		writeError(w, "session_id 必须非空且不超过 128 字符")
		return
	}
	if req.Message == "" || len([]rune(req.Message)) > maxMessageLen {
		writeError(w, "message 必须非空且不超过 4000 字符")
		return
	}
	lang := strings.ToLower(strings.TrimSpace(req.Language))
	if lang == "" {
		lang = domain.DefaultLanguage
	}
	if lang != "zh" && lang != "en" {
		writeError(w, "language 仅支持 zh/en")
		return
	}
	writeJSON(w, http.StatusOK, h.chat.Answer(req.SessionID, req.Message, lang))
}

func (h *Handlers) Healthz(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"project":   config.Project,
		"pack_ref":  config.PackRef,
		"redis":     h.sessions.RedisPing(),
		"languages": domain.Languages(),
	})
}

func (h *Handlers) Home(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, "仅支持 GET")
		return
	}
	h.indexHTML(w, r)
}

func writeHTML(w http.ResponseWriter, page []byte) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write(page)
}

// Admin 开发后台页（必含，只读）。
func (h *Handlers) Admin(w http.ResponseWriter, r *http.Request) {
	writeHTML(w, h.adminHTML)
}

// Console 业务人员后台页：开关未开启时 404，与 python/java 栈一致。
func (h *Handlers) Console(w http.ResponseWriter, r *http.Request) {
	if !config.BusinessConsole {
		writeJSON(w, http.StatusNotFound, map[string]string{"detail": "业务后台未开启"})
		return
	}
	writeHTML(w, h.consoleHTML)
}

// SessionDetail GET /sessions/{id}：调试页槽位回显，只读 Redis 易失状态。
func (h *Handlers) SessionDetail(w http.ResponseWriter, r *http.Request) {
	sessionID := strings.TrimPrefix(r.URL.Path, "/sessions/")
	if sessionID == "" || sessionID == r.URL.Path {
		writeError(w, "路径应为 /sessions/{session_id}")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"session_id": sessionID,
		"slots":      h.sessions.LoadSlots(sessionID),
	})
}

type adminOverviewBody struct {
	Project         string               `json:"project"`
	PackRef         string               `json:"pack_ref"`
	Redis           string               `json:"redis"`
	Languages       []string             `json:"languages"`
	ModelConfigured bool                 `json:"model_configured"`
	CoreMode        string               `json:"core_mode"`
	BusinessConsole bool                 `json:"business_console"`
	Rules           []domain.Rule        `json:"rules"`
	Skills          []domain.Skill       `json:"skills"`
	APIs            []domain.APIContract `json:"apis"`
}

// AdminOverview 开发后台总览：运行态 + 规则/技能/接口契约（编译进项目的数据文件）。
func (h *Handlers) AdminOverview(w http.ResponseWriter, r *http.Request) {
	rules, err := domain.LoadRules()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	skills, err := domain.LoadSkills()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	apis, err := domain.LoadAPIs()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"detail": err.Error()})
		return
	}
	if rules == nil {
		rules = []domain.Rule{}
	}
	if skills == nil {
		skills = []domain.Skill{}
	}
	if apis == nil {
		apis = []domain.APIContract{}
	}
	writeJSON(w, http.StatusOK, adminOverviewBody{
		Project:         config.Project,
		PackRef:         config.PackRef,
		Redis:           h.sessions.RedisPing(),
		Languages:       domain.Languages(),
		ModelConfigured: config.ModelBaseURL != "" && config.ModelName != "" && config.ModelAPIKey != "",
		CoreMode:        config.CoreMode,
		BusinessConsole: config.BusinessConsole,
		Rules:           rules,
		Skills:          skills,
		APIs:            apis,
	})
}

type consoleSessionRow struct {
	SessionID string `json:"session_id"`
	Flagged   string `json:"flagged"`
	Turns     any    `json:"turns"`
}

// ConsoleSessions 业务后台待关注会话列表：仅规则打标的会话。
func (h *Handlers) ConsoleSessions(w http.ResponseWriter, r *http.Request) {
	if !config.BusinessConsole {
		writeJSON(w, http.StatusNotFound, map[string]string{"detail": "业务后台未开启"})
		return
	}
	rows := make([]consoleSessionRow, 0)
	for _, item := range h.sessions.ListSessions() {
		flagged, _ := item.Slots["flagged"].(string)
		if flagged == "" {
			continue
		}
		turns := item.Slots["turns"]
		if turns == nil {
			turns = 0
		}
		rows = append(rows, consoleSessionRow{SessionID: item.SessionID, Flagged: flagged, Turns: turns})
	}
	writeJSON(w, http.StatusOK, rows)
}
