//! S5 代码生成：确定性骨架模板 + 槽位渲染，闸门A未生效则拒绝生成。
use crate::extract::RULES_ARTIFACT;
use crate::state::{self, StageId, StageStatus};
use crate::workspace::Workspace;
use anyhow::{bail, Context, Result};
use chrono::Utc;
use serde_json::Value;
use std::path::{Path, PathBuf};

/// 用户在生成文件头部任一行写入该标记，重生成即跳过此文件（定制层保护）。
pub const CUSTOM_MARKER: &str = "ICEWRIGHT-CUSTOM";

const ENGINE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// 目标栈为 python 时的骨架模板（目录结构遵循 docs-internal/12 的阿里 Python 分层）。
static TEMPLATES: &[(&str, &str)] = &[
    (
        "requirements.txt",
        include_str!("../templates/python/requirements.txt"),
    ),
    ("README.md", include_str!("../templates/python/README.md")),
    (
        ".env.example",
        include_str!("../templates/python/.env.example"),
    ),
    (".gitignore", include_str!("../templates/python/.gitignore")),
    (
        "app/__init__.py",
        include_str!("../templates/python/app/__init__.py"),
    ),
    (
        "app/main.py",
        include_str!("../templates/python/app/main.py"),
    ),
    (
        "app/config/__init__.py",
        include_str!("../templates/python/app/config/__init__.py"),
    ),
    (
        "app/config/settings.py",
        include_str!("../templates/python/app/config/settings.py"),
    ),
    (
        "app/api/__init__.py",
        include_str!("../templates/python/app/api/__init__.py"),
    ),
    (
        "app/api/routes.py",
        include_str!("../templates/python/app/api/routes.py"),
    ),
    (
        "app/service/__init__.py",
        include_str!("../templates/python/app/service/__init__.py"),
    ),
    (
        "app/service/session.py",
        include_str!("../templates/python/app/service/session.py"),
    ),
    (
        "app/service/chat.py",
        include_str!("../templates/python/app/service/chat.py"),
    ),
    (
        "app/domain/__init__.py",
        include_str!("../templates/python/app/domain/__init__.py"),
    ),
    (
        "app/domain/rules.py",
        include_str!("../templates/python/app/domain/rules.py"),
    ),
    (
        "app/integration/__init__.py",
        include_str!("../templates/python/app/integration/__init__.py"),
    ),
    (
        "app/integration/core_client.py",
        include_str!("../templates/python/app/integration/core_client.py"),
    ),
    (
        "tests/__init__.py",
        include_str!("../templates/python/tests/__init__.py"),
    ),
    (
        "tests/test_rules.py",
        include_str!("../templates/python/tests/test_rules.py"),
    ),
];

struct Slots {
    project_name: String,
    pack_ref: String,
    engine_version: String,
}

/// 渲染槽位；若仍残留 `{{`，说明模板/槽位表不同步——宁可失败不可写出半截占位符。
fn render(tpl: &str, rel: &str, slots: &Slots) -> Result<String> {
    let out = tpl
        .replace("{{project_name}}", &slots.project_name)
        .replace("{{pack_ref}}", &slots.pack_ref)
        .replace("{{engine_version}}", &slots.engine_version);
    if let Some(pos) = out.find("{{") {
        let around = &out[pos..out.len().min(pos + 40)];
        bail!("模板 {rel} 含未定义槽位: {around:?}");
    }
    Ok(out)
}

#[derive(Debug)]
pub struct GenerateReport {
    pub out_dir: PathBuf,
    pub written: Vec<String>,
    pub preserved: Vec<String>,
    pub output_hash: String,
}

fn has_custom_marker(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .map(|raw| {
            raw.lines()
                .take(3)
                .any(|l| l.contains(CUSTOM_MARKER) && !l.contains("# AUTO-GENERATED BY IceWright"))
        })
        .unwrap_or(false)
}

/// S5 执行体：要求闸门A对当前设计产物有效，渲染骨架并落盘到 out_dir。
pub fn generate(ws: &Workspace, out_dir: &Path) -> Result<GenerateReport> {
    let state_path = ws.state_path();
    if !state_path.exists() {
        bail!("请先 `icewright pipeline init {}`", ws.id);
    }
    let mut st = state::load_state(&state_path)?;
    if !st.gate_is_current(StageId::S4) {
        bail!("闸门A未生效：请先 `icewright design render` 并由 `icewright design approve` 确认；任何产物变更后需重新确认");
    }

    let rules_raw = std::fs::read_to_string(ws.artifact_path(RULES_ARTIFACT))
        .context("缺少 artifacts/rules.json，请先完成 S3 规则提取")?;
    let rules: Value = serde_json::from_str(&rules_raw)?;
    let errors = icewright_artifact::validate_instance("rules", &rules)?;
    if !errors.is_empty() {
        bail!("rules.json 违反契约，拒绝生成：{errors:?}");
    }

    let cfg = ws.config()?;
    let cfg_pack = if cfg.workspace.pack.is_empty() {
        None
    } else {
        Some(cfg.workspace.pack.clone())
    };
    let pack_ref = st
        .pack_ref
        .clone()
        .or(cfg_pack)
        .unwrap_or_else(|| "pack/unspecified".to_string());
    let slots = Slots {
        project_name: cfg.workspace.name.clone(),
        pack_ref,
        engine_version: ENGINE_VERSION.to_string(),
    };

    let mut written = Vec::new();
    let mut preserved = Vec::new();
    let mut hashed: Vec<String> = Vec::new();
    for (rel, tpl) in TEMPLATES {
        let target = out_dir.join(rel);
        if target.exists() && has_custom_marker(&target) {
            preserved.push(rel.to_string());
            if let Ok(raw) = std::fs::read_to_string(&target) {
                hashed.push(format!("{rel}\n{raw}"));
            }
            continue;
        }
        let content = render(tpl, rel, &slots)?;
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&target, &content)?;
        written.push(rel.to_string());
        hashed.push(format!("{rel}\n{content}"));
    }

    // 规则产物编译进项目（数据不是模板，重生成始终覆盖）
    hashed.push(format!("app/data/rules.json\n{rules_raw}"));
    let data_dir = out_dir.join("app/data");
    std::fs::create_dir_all(&data_dir)?;
    std::fs::write(data_dir.join("rules.json"), &rules_raw)?;

    hashed.sort();
    let output_hash = state::sha256_hex(hashed.join("\n---\n").as_bytes());

    let cfg_raw = std::fs::read(ws.root.join("icewright.toml"))?;
    let template_bytes: Vec<&[u8]> = TEMPLATES.iter().map(|(_, t)| t.as_bytes()).collect();
    let mut input_parts: Vec<&[u8]> = vec![rules_raw.as_bytes(), &cfg_raw];
    input_parts.extend(template_bytes.iter().copied());
    let in_hash = state::input_hash(&input_parts);

    let now = Utc::now();
    if let Some(s) = st.stages.iter_mut().find(|s| s.id == StageId::S5) {
        s.status = StageStatus::Approved;
        s.input_hash = Some(in_hash);
        s.output_hash = Some(output_hash.clone());
        s.started_at = Some(now);
        s.ended_at = Some(now);
        s.failures.clear();
    }
    if st.current_stage == StageId::S4 || st.current_stage == StageId::S5 {
        st.current_stage = StageId::S6;
    }
    st.updated_at = Some(now);
    state::save_state(&state_path, &st)?;

    Ok(GenerateReport {
        out_dir: out_dir.to_path_buf(),
        written,
        preserved,
        output_hash,
    })
}

/// 供测试与 S8 重生成使用：直接把某阶段置为已批准。
#[cfg(test)]
pub(crate) fn approve_stage(st: &mut state::PipelineState, id: StageId, out: &str, gate: bool) {
    use crate::state::{GateDecision, GateRecord};
    let now = Utc::now();
    if let Some(s) = st.stages.iter_mut().find(|s| s.id == id) {
        s.status = StageStatus::Approved;
        s.output_hash = Some(out.to_string());
        s.started_at = Some(now);
        s.ended_at = Some(now);
        if gate {
            s.gate = Some(GateRecord {
                decision: GateDecision::Approved,
                by: "tester".to_string(),
                at: now,
                artifact_hash: out.to_string(),
                note: None,
                role: None,
            });
        }
    }
    st.current_stage = id;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::PipelineState;
    use std::sync::atomic::{AtomicU32, Ordering};

    static SEQ: AtomicU32 = AtomicU32::new(0);

    fn setup(tag: &str) -> Workspace {
        let base = std::env::temp_dir().join(format!("iw-gen-{}-{}", tag, std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let ws = Workspace::create_at(
            &base,
            &format!("gen-{tag}-{}", SEQ.fetch_add(1, Ordering::SeqCst)),
        )
        .unwrap();
        let cfg_path = ws.root.join("icewright.toml");
        let raw = std::fs::read_to_string(&cfg_path)
            .unwrap()
            .replace("pack = \"\"", "pack = \"insurance/auto-claim@0.1.0\"");
        std::fs::write(&cfg_path, raw).unwrap();

        let rules = icewright_artifact::example("rules").unwrap();
        std::fs::write(
            ws.artifact_path(RULES_ARTIFACT),
            serde_json::to_string_pretty(&rules).unwrap(),
        )
        .unwrap();

        let mut st = PipelineState::new(&ws.id, "run-test", Some("insurance/auto-claim@0.1.0"));
        for id in [StageId::S1, StageId::S2, StageId::S3] {
            approve_stage(&mut st, id, &state::sha256_hex(id.title().as_bytes()), false);
        }
        approve_stage(
            &mut st,
            StageId::S4,
            &state::sha256_hex(b"design-doc"),
            true,
        );
        state::save_state(&ws.state_path(), &st).unwrap();
        ws
    }

    #[test]
    fn renders_all_templates_and_advances_s5() {
        let ws = setup("render");
        let out = ws.root.join("output");
        let report = generate(&ws, &out).unwrap();
        assert!(report.preserved.is_empty());
        assert_eq!(report.written.len(), TEMPLATES.len());
        let main_py = std::fs::read_to_string(out.join("app/main.py")).unwrap();
        assert!(main_py.contains(&ws.id), "project_name 槽位应渲染");
        assert!(!main_py.contains("{{"));
        assert!(out.join("app/data/rules.json").exists());

        let st = state::load_state(&ws.state_path()).unwrap();
        assert_eq!(st.stage(StageId::S5).unwrap().status, StageStatus::Approved);
        assert_eq!(st.current_stage, StageId::S6);

        // 幂等：再次生成，产物哈希不变
        let report2 = generate(&ws, &out).unwrap();
        assert_eq!(report.output_hash, report2.output_hash);
    }

    #[test]
    fn preserves_custom_layer_files() {
        let ws = setup("custom");
        let out = ws.root.join("output");
        std::fs::create_dir_all(out.join("app")).unwrap();
        std::fs::write(out.join("app/main.py"), "# ICEWRIGHT-CUSTOM\nMY CODE\n").unwrap();
        let report = generate(&ws, &out).unwrap();
        assert_eq!(report.preserved, vec!["app/main.py".to_string()]);
        assert_eq!(
            std::fs::read_to_string(out.join("app/main.py")).unwrap(),
            "# ICEWRIGHT-CUSTOM\nMY CODE\n"
        );
    }

    #[test]
    fn stale_gate_blocks_generation() {
        let ws = setup("stale");
        // 模拟产物变更：设计文档哈希漂移，闸门批准失效
        let p = ws.state_path();
        let mut st = state::load_state(&p).unwrap();
        if let Some(s) = st.stages.iter_mut().find(|s| s.id == StageId::S4) {
            s.output_hash = Some(state::sha256_hex(b"changed-design"));
        }
        state::save_state(&p, &st).unwrap();
        let err = generate(&ws, &ws.root.join("output")).unwrap_err();
        assert!(err.to_string().contains("闸门A未生效"), "{err}");
    }
}
